caidabgp_stream_web_data_broker_meta:
    path:     /meta
    defaults: { _controller: CAIDABGPStreamWebDataBrokerBundle:Default:meta }

caidabgp_stream_web_data_broker_data:
    path:     /data
    defaults: { _controller: CAIDABGPStreamWebDataBrokerBundle:Default:data }
