caida_bgpstream_web_data_broker_meta_project:
    path:     /meta/projects/{project}
    defaults:
        _controller: CAIDABGPStreamWebDataBrokerBundle:Default:metaProjects
        project: all

caida_bgpstream_web_data_broker_meta_collector:
    path:     /meta/collectors/{collector}
    defaults:
        _controller: CAIDABGPStreamWebDataBrokerBundle:Default:metaCollectors
        collector: all

caida_bgpstream_web_data_broker_data:
    path:     /data
    defaults: { _controller: CAIDABGPStreamWebDataBrokerBundle:Default:data }

caida_bgpstream_web_data_broker_test:
    path:     /test
    defaults: { _controller: CAIDABGPStreamWebDataBrokerBundle:Default:test }
