caidabgp_stream_web_data_broker_meta:
    path:     /meta/{project}/{collector}
    defaults:
        _controller: CAIDABGPStreamWebDataBrokerBundle:Default:meta
        project: all
        collector: all

caidabgp_stream_web_data_broker_data:
    path:     /data
    defaults: { _controller: CAIDABGPStreamWebDataBrokerBundle:Default:data }
