bgpstream_utils_addr_set.h File Reference
Header file that exposes the public interface of the BGP Stream Address Sets.
Typedefs
Opaque Data Structures
typedef struct
bgpstream_addr_storage_set bgpstream_addr_storage_set_t
Opaque structure containing an Address Storage set instance.
typedef struct
bgpstream_ipv4_addr_set bgpstream_ipv4_addr_set_t
Opaque structure containing an IPv4 Address set instance.
typedef struct
bgpstream_ipv6_addr_set bgpstream_ipv6_addr_set_t
Opaque structure containing an IPv6 Address set instance.
Functions
Public API Functions
bgpstream_addr_storage_set_t * bgpstream_addr_storage_set_create ()
Create a new Address Storage set instance.
int bgpstream_addr_storage_set_insert (bgpstream_addr_storage_set_t *set, bgpstream_addr_storage_t *addr)
Insert a new address into the given set.
int bgpstream_addr_storage_set_size (bgpstream_addr_storage_set_t *set)
Get the number of addresses in the given set.
int bgpstream_addr_storage_set_merge (bgpstream_addr_storage_set_t *dst_set, bgpstream_addr_storage_set_t *src_set)
Merge two address sets.
void bgpstream_addr_storage_set_destroy (bgpstream_addr_storage_set_t *set)
Destroy the given address set.
void bgpstream_addr_storage_set_clear (bgpstream_addr_storage_set_t *set)
Empty the address set.
bgpstream_ipv4_addr_set_t * bgpstream_ipv4_addr_set_create ()
Create a new IPv4 Address set instance.
int bgpstream_ipv4_addr_set_insert (bgpstream_ipv4_addr_set_t *set, bgpstream_ipv4_addr_t *addr)
Insert a new address into the given set.
int bgpstream_ipv4_addr_set_size (bgpstream_ipv4_addr_set_t *set)
Get the number of addresses in the given set.
int bgpstream_ipv4_addr_set_merge (bgpstream_ipv4_addr_set_t *dst_set, bgpstream_ipv4_addr_set_t *src_set)
Merge two address sets.
void bgpstream_ipv4_addr_set_destroy (bgpstream_ipv4_addr_set_t *set)
Destroy the given address set.
void bgpstream_ipv4_addr_set_clear (bgpstream_ipv4_addr_set_t *set)
Empty the address set.
bgpstream_ipv6_addr_set_t * bgpstream_ipv6_addr_set_create ()
Create a new IPv6 Address set instance.
int bgpstream_ipv6_addr_set_insert (bgpstream_ipv6_addr_set_t *set, bgpstream_ipv6_addr_t *addr)
Insert a new address into the given set.
int bgpstream_ipv6_addr_set_size (bgpstream_ipv6_addr_set_t *set)
Get the number of addresses in the given set.
int bgpstream_ipv6_addr_set_merge (bgpstream_ipv6_addr_set_t *dst_set, bgpstream_ipv6_addr_set_t *src_set)
Merge two address sets.
void bgpstream_ipv6_addr_set_destroy (bgpstream_ipv6_addr_set_t *set)
Destroy the given address set.
void bgpstream_ipv6_addr_set_clear (bgpstream_ipv6_addr_set_t *set)
Empty the address set.
Detailed Description
Header file that exposes the public interface of the BGP Stream Address Sets.
There is one set for each bgpstream_addr type (Storage, IPv4 and IPv6).
Author
Chiara Orsini
Definition in file bgpstream_utils_addr_set.h.
Typedef Documentation
typedef struct bgpstream_addr_storage_set bgpstream_addr_storage_set_t
Opaque structure containing an Address Storage set instance.
Definition at line 46 of file bgpstream_utils_addr_set.h.
typedef struct bgpstream_ipv4_addr_set bgpstream_ipv4_addr_set_t
Opaque structure containing an IPv4 Address set instance.
Definition at line 49 of file bgpstream_utils_addr_set.h.
typedef struct bgpstream_ipv6_addr_set bgpstream_ipv6_addr_set_t
Opaque structure containing an IPv6 Address set instance.
Definition at line 52 of file bgpstream_utils_addr_set.h.
Function Documentation
void bgpstream_addr_storage_set_clear (bgpstream_addr_storage_set_t * set)
Empty the address set.
Parameters
set pointer to the address set to clear
Definition at line 153 of file bgpstream_utils_addr_set.c.
bgpstream_addr_storage_set_t* bgpstream_addr_storage_set_create ()
Create a new Address Storage set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 90 of file bgpstream_utils_addr_set.c.
References bgpstream_addr_storage_set_destroy().
void bgpstream_addr_storage_set_destroy (bgpstream_addr_storage_set_t * set)
Destroy the given address set.
Parameters
set pointer to the address set to destroy
Definition at line 147 of file bgpstream_utils_addr_set.c.
Referenced by bgpstream_addr_storage_set_create().
int bgpstream_addr_storage_set_insert (bgpstream_addr_storage_set_t * set, bgpstream_addr_storage_t * addr)
Insert a new address into the given set.
Parameters
set pointer to the address set
addr address to insert in the set
Returns
1 if the address was inserted, 0 if it already existed, -1 if an error occurred
Definition at line 110 of file bgpstream_utils_addr_set.c.
Referenced by bgpstream_addr_storage_set_merge().
int bgpstream_addr_storage_set_merge (bgpstream_addr_storage_set_t * dst_set, bgpstream_addr_storage_set_t * src_set)
Merge two address sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 129 of file bgpstream_utils_addr_set.c.
References bgpstream_addr_storage_set_insert().
int bgpstream_addr_storage_set_size (bgpstream_addr_storage_set_t * set)
Get the number of addresses in the given set.
Parameters
set pointer to the address set
Returns
the size of the address set
Definition at line 124 of file bgpstream_utils_addr_set.c.
void bgpstream_ipv4_addr_set_clear (bgpstream_ipv4_addr_set_t * set)
Empty the address set.
Parameters
set pointer to the address set to clear
Definition at line 225 of file bgpstream_utils_addr_set.c.
bgpstream_ipv4_addr_set_t* bgpstream_ipv4_addr_set_create ()
Create a new IPv4 Address set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 162 of file bgpstream_utils_addr_set.c.
References bgpstream_ipv4_addr_set_destroy().
void bgpstream_ipv4_addr_set_destroy (bgpstream_ipv4_addr_set_t * set)
Destroy the given address set.
Parameters
set pointer to the address set to destroy
Definition at line 219 of file bgpstream_utils_addr_set.c.
Referenced by bgpstream_ipv4_addr_set_create().
int bgpstream_ipv4_addr_set_insert (bgpstream_ipv4_addr_set_t * set, bgpstream_ipv4_addr_t * addr)
Insert a new address into the given set.
Parameters
set pointer to the address set
addr address to insert in the set
Returns
1 if the address was inserted, 0 if it already existed, -1 if an error occurred
This function takes a copy of the address before it is inserted in the set.
Definition at line 182 of file bgpstream_utils_addr_set.c.
Referenced by bgpstream_ipv4_addr_set_merge().
int bgpstream_ipv4_addr_set_merge (bgpstream_ipv4_addr_set_t * dst_set, bgpstream_ipv4_addr_set_t * src_set)
Merge two address sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 201 of file bgpstream_utils_addr_set.c.
References bgpstream_ipv4_addr_set_insert().
int bgpstream_ipv4_addr_set_size (bgpstream_ipv4_addr_set_t * set)
Get the number of addresses in the given set.
Parameters
set pointer to the address set
Returns
the size of the address set
Definition at line 196 of file bgpstream_utils_addr_set.c.
void bgpstream_ipv6_addr_set_clear (bgpstream_ipv6_addr_set_t * set)
Empty the address set.
Parameters
set pointer to the address set to clear
Definition at line 297 of file bgpstream_utils_addr_set.c.
bgpstream_ipv6_addr_set_t* bgpstream_ipv6_addr_set_create ()
Create a new IPv6 Address set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 234 of file bgpstream_utils_addr_set.c.
References bgpstream_ipv6_addr_set_destroy().
void bgpstream_ipv6_addr_set_destroy (bgpstream_ipv6_addr_set_t * set)
Destroy the given address set.
Parameters
set pointer to the address set to destroy
Definition at line 291 of file bgpstream_utils_addr_set.c.
Referenced by bgpstream_ipv6_addr_set_create().
int bgpstream_ipv6_addr_set_insert (bgpstream_ipv6_addr_set_t * set, bgpstream_ipv6_addr_t * addr)
Insert a new address into the given set.
Parameters
set pointer to the address set
addr address to insert in the set
Returns
1 if the address was inserted, 0 if it already existed, -1 if an error occurred
Definition at line 254 of file bgpstream_utils_addr_set.c.
Referenced by bgpstream_ipv6_addr_set_merge().
int bgpstream_ipv6_addr_set_merge (bgpstream_ipv6_addr_set_t * dst_set, bgpstream_ipv6_addr_set_t * src_set)
Merge two address sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 273 of file bgpstream_utils_addr_set.c.
References bgpstream_ipv6_addr_set_insert().
int bgpstream_ipv6_addr_set_size (bgpstream_ipv6_addr_set_t * set)
Get the number of addresses in the given set.
Parameters
set pointer to the address set
Returns
the size of the address set
Definition at line 268 of file bgpstream_utils_addr_set.c.