bgpstream_utils_addr.h File Reference
Header file that exposes the public interface of BGP Stream Address objects.
Data Structures
struct struct_bgpstream_ip_addr_t
A generic BGP Stream IP address.
struct struct_bgpstream_ipv4_addr_t
An IPv4 BGP Stream IP address.
struct struct_bgpstream_ipv6_addr_t
An IPv6 BGP Stream IP address.
struct struct_bgpstream_addr_storage_t
Generic storage for a BGP Stream IP address.
Typedefs
Public Data Structures
typedef struct
struct_bgpstream_ip_addr_t bgpstream_ip_addr_t
A generic BGP Stream IP address.
typedef struct
struct_bgpstream_ipv4_addr_t bgpstream_ipv4_addr_t
An IPv4 BGP Stream IP address.
typedef struct
struct_bgpstream_ipv6_addr_t bgpstream_ipv6_addr_t
An IPv6 BGP Stream IP address.
typedef struct
struct_bgpstream_addr_storage_t bgpstream_addr_storage_t
Generic storage for a BGP Stream IP address.
Public Enums
#define BGPSTREAM_MAX_IP_VERSION_IDX 2
Maximum number of IP versions.
enum bgpstream_addr_version_t { BGPSTREAM_ADDR_VERSION_UNKNOWN = 0, BGPSTREAM_ADDR_VERSION_IPV4 = AF_INET, BGPSTREAM_ADDR_VERSION_IPV6 = AF_INET6 }
Version of a BGP Stream IP Address.
Public API Functions
#define bgpstream_addr_ntop(buf, len, bsaddr)
Write the string representation of the given IP address into the given character buffer.
bgpstream_ipv4_addr_hash (bgpstream_ipv4_addr_t *addr)
Hash the given IPv4 address into a 32bit number.
unsigned long bgpstream_ipv6_addr_hash (bgpstream_ipv6_addr_t *addr)
Hash the given IPv6 address into a 64bit number.
unsigned long bgpstream_addr_storage_hash (bgpstream_addr_storage_t *addr)
Hash the given address storage into a 64bit number.
int bgpstream_ipv4_addr_equal (bgpstream_ipv4_addr_t *addr1, bgpstream_ipv4_addr_t *addr2)
Compare two IPv4 addresses for equality.
int bgpstream_ipv6_addr_equal (bgpstream_ipv6_addr_t *addr1, bgpstream_ipv6_addr_t *addr2)
Compare two IPv6 addresses for equality.
int bgpstream_addr_storage_equal (bgpstream_addr_storage_t *addr1, bgpstream_addr_storage_t *ip2)
Compare two generic addresses for equality.
uint8_t bgpstream_ipv2idx (bgpstream_addr_version_t v)
Returns the index associated to an IP version.
bgpstream_addr_version_t bgpstream_idx2ipv (uint8_t i)
Returns the IP version associated with an index.
uint8_t bgpstream_ipv2number (bgpstream_addr_version_t v)
Returns the number associated to an IP version.
uint8_t bgpstream_idx2number (uint8_t i)
Returns the number associated to the index (associated to an IP version)
Detailed Description
Header file that exposes the public interface of BGP Stream Address objects.
Author
Chiara Orsini
Definition in file bgpstream_utils_addr.h.
Macro Definition Documentation
#define bgpstream_addr_ntop (buf, len, bsaddr)
Value:
inet_ntop((bsaddr)->version,                                          \
            &(((bgpstream_ip_addr_t*)(bsaddr))->addr),                  \
            buf, len)
Write the string representation of the given IP address into the given character buffer.
Parameters
buf pointer to a character buffer at least len bytes long
len length of the given character buffer
bsaddr pointer to the bgpstream addr to convert to string
You will likely want to use INET_ADDRSTRLEN or INET6_ADDRSTRLEN to dimension the buffer.
Definition at line 150 of file bgpstream_utils_addr.h.
Referenced by bgpstream_elem_snprintf(), and bgpstream_pfx_snprintf().
#define BGPSTREAM_MAX_IP_VERSION_IDX 2
Maximum number of IP versions.
Definition at line 69 of file bgpstream_utils_addr.h.
Typedef Documentation
typedef struct struct_bgpstream_addr_storage_t bgpstream_addr_storage_t
Generic storage for a BGP Stream IP address.
typedef struct struct_bgpstream_ip_addr_t bgpstream_ip_addr_t
A generic BGP Stream IP address.
Must only be used for casting to the appropriate type based on the version
typedef struct struct_bgpstream_ipv4_addr_t bgpstream_ipv4_addr_t
An IPv4 BGP Stream IP address.
typedef struct struct_bgpstream_ipv6_addr_t bgpstream_ipv6_addr_t
An IPv6 BGP Stream IP address.
Enumeration Type Documentation
enum bgpstream_addr_version_t
Version of a BGP Stream IP Address.
These share values with AF_INET and AF_INET6 so that the version field of a BGP Stream address can be used directly with standard address manipulation functions
Enumerator
BGPSTREAM_ADDR_VERSION_UNKNOWN
Address type unknown.
BGPSTREAM_ADDR_VERSION_IPV4
Address type IPv4.
BGPSTREAM_ADDR_VERSION_IPV6
Address type IPv6.
Definition at line 55 of file bgpstream_utils_addr.h.
Function Documentation
int bgpstream_addr_storage_equal (bgpstream_addr_storage_t * addr1, bgpstream_addr_storage_t * ip2)
Compare two generic addresses for equality.
Parameters
addr1 pointer to the first address to compare
addr2 pointer to the second address to compare
Returns
0 if the addresses are not equal, non-zero if they are equal
Definition at line 79 of file bgpstream_utils_addr.c.
References BGPSTREAM_ADDR_VERSION_IPV4, BGPSTREAM_ADDR_VERSION_IPV6, bgpstream_ipv4_addr_equal(), bgpstream_ipv6_addr_equal(), and struct_bgpstream_addr_storage_t::version.
Referenced by bgpstream_pfx_storage_equal().
unsigned long bgpstream_addr_storage_hash (bgpstream_addr_storage_t * addr)
Hash the given address storage into a 64bit number.
Parameters
addr pointer to the address to hash
Returns
64bit hash of the address
Definition at line 60 of file bgpstream_utils_addr.c.
References BGPSTREAM_ADDR_VERSION_IPV4, BGPSTREAM_ADDR_VERSION_IPV6, bgpstream_ipv4_addr_hash(), bgpstream_ipv6_addr_hash(), and struct_bgpstream_addr_storage_t::version.
bgpstream_addr_version_t bgpstream_idx2ipv (uint8_t i)
Returns the IP version associated with an index.
Parameters
i index associated to the IP address version
Returns
the IP version associated with an index
Definition at line 132 of file bgpstream_utils_addr.c.
References BGPSTREAM_ADDR_VERSION_IPV4, BGPSTREAM_ADDR_VERSION_IPV6, and BGPSTREAM_ADDR_VERSION_UNKNOWN.
uint8_t bgpstream_idx2number (uint8_t i)
Returns the number associated to the index (associated to an IP version)
Parameters
i index associated to the IP address version
Returns
the index number, 255 if there is an error in the translation
Definition at line 165 of file bgpstream_utils_addr.c.
uint8_t bgpstream_ipv2idx (bgpstream_addr_version_t v)
Returns the index associated to an IP version.
Parameters
v enum rapresenting the IP address version
Returns
the index associated with the IP version, 255 if there is an error in the translation
Definition at line 117 of file bgpstream_utils_addr.c.
References BGPSTREAM_ADDR_VERSION_IPV4, and BGPSTREAM_ADDR_VERSION_IPV6.
uint8_t bgpstream_ipv2number (bgpstream_addr_version_t v)
Returns the number associated to an IP version.
Parameters
v enum rapresenting the IP address version
Returns
the IP version number, 255 if there is an error in the translation
Definition at line 149 of file bgpstream_utils_addr.c.
References BGPSTREAM_ADDR_VERSION_IPV4, and BGPSTREAM_ADDR_VERSION_IPV6.
int bgpstream_ipv4_addr_equal (bgpstream_ipv4_addr_t * addr1, bgpstream_ipv4_addr_t * addr2)
Compare two IPv4 addresses for equality.
Parameters
addr1 pointer to the first address to compare
addr2 pointer to the second address to compare
Returns
0 if the addresses are not equal, non-zero if they are equal
Definition at line 98 of file bgpstream_utils_addr.c.
References struct_bgpstream_ipv4_addr_t::ipv4.
Referenced by bgpstream_addr_storage_equal(), and bgpstream_ipv4_pfx_equal().
bgpstream_ipv4_addr_hash (bgpstream_ipv4_addr_t * addr)
Hash the given IPv4 address into a 32bit number.
Parameters
addr pointer to the IPv4 address to hash
Returns
32bit hash of the address
Definition at line 37 of file bgpstream_utils_addr.c.
References struct_bgpstream_ipv4_addr_t::ipv4.
Referenced by bgpstream_addr_storage_hash().
int bgpstream_ipv6_addr_equal (bgpstream_ipv6_addr_t * addr1, bgpstream_ipv6_addr_t * addr2)
Compare two IPv6 addresses for equality.
Parameters
addr1 pointer to the first address to compare
addr2 pointer to the second address to compare
Returns
0 if the addresses are not equal, non-zero if they are equal
Definition at line 105 of file bgpstream_utils_addr.c.
References struct_bgpstream_ipv6_addr_t::ipv6.
Referenced by bgpstream_addr_storage_equal(), and bgpstream_ipv6_pfx_equal().
unsigned long bgpstream_ipv6_addr_hash (bgpstream_ipv6_addr_t * addr)
Hash the given IPv6 address into a 64bit number.
Parameters
addr pointer to the IPv6 address to hash
Returns
64bit hash of the address
Definition at line 48 of file bgpstream_utils_addr.c.
References struct_bgpstream_ipv6_addr_t::ipv6.
Referenced by bgpstream_addr_storage_hash().