bgpstream_utils_as_path_int.h File Reference
Header file that exposes the private interface of BGP Stream AS objects.
Data Structures
struct bgpstream_as_path
Functions
Private API Functions
int bgpstream_as_path_populate (bgpstream_as_path_t *path, struct aspath *bd_path)
Populate an AS Path structure based on a BGP Dump AS Path Attribute.
void bgpstream_as_path_update_fields (bgpstream_as_path_t *path)
Update the internal fields once the data array has been changed.
Detailed Description
Header file that exposes the private interface of BGP Stream AS objects.
Author
Chiara Orsini, Alistair King
Definition in file bgpstream_utils_as_path_int.h.
Function Documentation
int bgpstream_as_path_populate (bgpstream_as_path_t * path, struct aspath * bd_path)
Populate an AS Path structure based on a BGP Dump AS Path Attribute.
Parameters
path pointer to the AS Path to populate
bd_path pointer to a BGP Dump AS Path attribute structure
Returns
0 if the path was populated successfully, -1 otherwise
Todo:
consider merging consecutive segments of the same type?
Definition at line 636 of file bgpstream_utils_as_path.c.
References asn, bgpstream_as_path_clear(), bgpstream_as_path_iter_reset(), BGPSTREAM_AS_PATH_SEG_ASN, BGPSTREAM_AS_PATH_SEG_CONFED_SEQ, BGPSTREAM_AS_PATH_SEG_CONFED_SET, BGPSTREAM_AS_PATH_SEG_SET, bgpstream_as_path_snprintf(), bgpstream_as_path::seg_cnt, and bgpstream_as_path_seg::type.
void bgpstream_as_path_update_fields (bgpstream_as_path_t * path)
Update the internal fields once the data array has been changed.
Parameters
path pointer to the AS Path to update
Definition at line 823 of file bgpstream_utils_as_path.c.
References bgpstream_as_path_get_next_seg(), bgpstream_as_path_iter_reset(), and bgpstream_as_path::seg_cnt.
Referenced by bgpstream_as_path_populate_from_data(), bgpstream_as_path_populate_from_data_zc(), and bgpstream_as_path_store_path_get_path().