bgpstream_utils_pfx.h File Reference
Header file that exposes the public interface of BGP Stream Prefix objects.
Data Structures
struct struct_bgpstream_pfx_t
A generic BGP Stream Prefix.
struct struct_bgpstream_ipv4_pfx_t
An IPv4 BGP Stream Prefix.
struct struct_bgpstream_ipv6_pfx_t
An IPv6 BGP Stream Prefix.
struct struct_bgpstream_pfx_storage_t
Generic storage for a BGP Stream Prefix.
Typedefs
Public Data Structures
typedef struct
struct_bgpstream_pfx_t bgpstream_pfx_t
A generic BGP Stream Prefix.
typedef struct
struct_bgpstream_ipv4_pfx_t bgpstream_ipv4_pfx_t
An IPv4 BGP Stream Prefix.
typedef struct
struct_bgpstream_ipv6_pfx_t bgpstream_ipv6_pfx_t
An IPv6 BGP Stream Prefix.
typedef struct
struct_bgpstream_pfx_storage_t bgpstream_pfx_storage_t
Generic storage for a BGP Stream Prefix.
Public API Functions
#define bgpstream_pfx_storage_hash_val(arg) bgpstream_pfx_storage_hash(&(arg))
Utility macros used to pass khashes objects by reference instead of copying them.
#define bgpstream_pfx_storage_equal_val(arg1, arg2) bgpstream_pfx_storage_equal(&(arg1), &(arg2))
#define bgpstream_ipv4_pfx_storage_hash_val(arg) bgpstream_ipv4_pfx_hash(&(arg))
#define bgpstream_ipv4_pfx_storage_equal_val(arg1, arg2) bgpstream_ipv4_pfx_equal(&(arg1), &(arg2))
#define bgpstream_ipv6_pfx_storage_hash_val(arg) bgpstream_ipv6_pfx_hash(&(arg))
#define bgpstream_ipv6_pfx_storage_equal_val(arg1, arg2) bgpstream_ipv6_pfx_equal(&(arg1), &(arg2))
char * bgpstream_pfx_snprintf (char *buf, size_t len, bgpstream_pfx_t *pfx)
Write the string representation of the given prefix into the given character buffer.
bgpstream_ipv4_pfx_hash (bgpstream_ipv4_pfx_t *pfx)
Hash the given IPv4 Prefix into a 32bit number.
unsigned long bgpstream_ipv6_pfx_hash (bgpstream_ipv6_pfx_t *pfx)
Hash the given IPv6 prefix into a 64bit number.
unsigned long bgpstream_pfx_storage_hash (bgpstream_pfx_storage_t *pfx)
Hash the given prefix storage into a 64bit number.
int bgpstream_ipv4_pfx_equal (bgpstream_ipv4_pfx_t *pfx1, bgpstream_ipv4_pfx_t *pfx2)
Compare two IPv4 prefixes for equality.
int bgpstream_ipv6_pfx_equal (bgpstream_ipv6_pfx_t *pfx1, bgpstream_ipv6_pfx_t *pfx2)
Compare two IPv6 prefixes for equality.
int bgpstream_pfx_storage_equal (bgpstream_pfx_storage_t *pfx1, bgpstream_pfx_storage_t *pfx2)
Compare two generic prefixes for equality.
Detailed Description
Header file that exposes the public interface of BGP Stream Prefix objects.
Author
Chiara Orsini
Definition in file bgpstream_utils_pfx.h.
Macro Definition Documentation
#define bgpstream_pfx_storage_hash_val (arg) bgpstream_pfx_storage_hash(&(arg))
Utility macros used to pass khashes objects by reference instead of copying them.
Definition at line 187 of file bgpstream_utils_pfx.h.
Typedef Documentation
typedef struct struct_bgpstream_ipv4_pfx_t bgpstream_ipv4_pfx_t
An IPv4 BGP Stream Prefix.
typedef struct struct_bgpstream_ipv6_pfx_t bgpstream_ipv6_pfx_t
An IPv6 BGP Stream Prefix.
typedef struct struct_bgpstream_pfx_storage_t bgpstream_pfx_storage_t
Generic storage for a BGP Stream Prefix.
typedef struct struct_bgpstream_pfx_t bgpstream_pfx_t
A generic BGP Stream Prefix.
Must only be used for casting to the appropriate type based on the address version
Function Documentation
int bgpstream_ipv4_pfx_equal (bgpstream_ipv4_pfx_t * pfx1, bgpstream_ipv4_pfx_t * pfx2)
Compare two IPv4 prefixes for equality.
Parameters
pfx1 pointer to the first prefix to compare
pfx2 pointer to the second prefix to compare
Returns
0 if the prefixes are not equal, non-zero if they are equal
Definition at line 100 of file bgpstream_utils_pfx.c.
References struct_bgpstream_ipv4_pfx_t::address, bgpstream_ipv4_addr_equal(), and struct_bgpstream_ipv4_pfx_t::mask_len.
bgpstream_ipv4_pfx_hash (bgpstream_ipv4_pfx_t * pfx)
Hash the given IPv4 Prefix into a 32bit number.
Parameters
pfx pointer to the IPv4 prefix to hash
Returns
32bit hash of the prefix
Definition at line 59 of file bgpstream_utils_pfx.c.
References struct_bgpstream_ipv4_pfx_t::address, struct_bgpstream_ipv4_addr_t::ipv4, and struct_bgpstream_ipv4_pfx_t::mask_len.
Referenced by bgpstream_pfx_storage_hash().
int bgpstream_ipv6_pfx_equal (bgpstream_ipv6_pfx_t * pfx1, bgpstream_ipv6_pfx_t * pfx2)
Compare two IPv6 prefixes for equality.
Parameters
pfx1 pointer to the first prefix to compare
pfx2 pointer to the second prefix to compare
Returns
0 if the prefixes are not equal, non-zero if they are equal
Definition at line 108 of file bgpstream_utils_pfx.c.
References struct_bgpstream_ipv6_pfx_t::address, bgpstream_ipv6_addr_equal(), and struct_bgpstream_ipv6_pfx_t::mask_len.
unsigned long bgpstream_ipv6_pfx_hash (bgpstream_ipv6_pfx_t * pfx)
Hash the given IPv6 prefix into a 64bit number.
Parameters
pfx pointer to the IPv6 prefix to hash
Returns
64bit hash of the prefix
Definition at line 71 of file bgpstream_utils_pfx.c.
References struct_bgpstream_ipv6_pfx_t::address, struct_bgpstream_ipv6_addr_t::ipv6, and struct_bgpstream_ipv6_pfx_t::mask_len.
Referenced by bgpstream_pfx_storage_hash().
char* bgpstream_pfx_snprintf (char * buf, size_t len, bgpstream_pfx_t * pfx)
Write the string representation of the given prefix into the given character buffer.
Parameters
buf pointer to a character buffer at least len bytes long
len length of the given character buffer
pfx pointer to the bgpstream pfx to convert to string
returns a pointer to buf if successful, NULL otherwise
You will likely want to use INET_ADDRSTRLEN+3 or INET6_ADDRSTRLEN+3 to dimension the buffer.
Definition at line 31 of file bgpstream_utils_pfx.c.
References struct_bgpstream_pfx_t::address, bgpstream_addr_ntop, and struct_bgpstream_pfx_t::mask_len.
Referenced by bgpstream_elem_snprintf().
int bgpstream_pfx_storage_equal (bgpstream_pfx_storage_t * pfx1, bgpstream_pfx_storage_t * pfx2)
Compare two generic prefixes for equality.
Parameters
pfx1 pointer to the first prefix to compare
pfx2 pointer to the second prefix to compare
Returns
0 if the prefixes are not equal, non-zero if they are equal
Definition at line 118 of file bgpstream_utils_pfx.c.
References struct_bgpstream_pfx_storage_t::address, bgpstream_addr_storage_equal(), and struct_bgpstream_pfx_storage_t::mask_len.
unsigned long bgpstream_pfx_storage_hash (bgpstream_pfx_storage_t * pfx)
Hash the given prefix storage into a 64bit number.
Parameters
pfx pointer to the prefix to hash
Returns
64bit hash of the prefix
Definition at line 86 of file bgpstream_utils_pfx.c.
References struct_bgpstream_pfx_storage_t::address, BGPSTREAM_ADDR_VERSION_IPV4, BGPSTREAM_ADDR_VERSION_IPV6, bgpstream_ipv4_pfx_hash(), bgpstream_ipv6_pfx_hash(), and struct_bgpstream_addr_storage_t::version.