bgpstream_utils_str_set.h File Reference
Header file that exposes the public interface of the BGP Stream String Set.
Typedefs
Opaque Data Structures
typedef struct bgpstream_str_set_t bgpstream_str_set_t
Opaque structure containing a string set instance.
Functions
Public API Functions
bgpstream_str_set_t * bgpstream_str_set_create ()
Create a new string set instance.
int bgpstream_str_set_insert (bgpstream_str_set_t *set, char *val)
Insert a new string into the string set.
int bgpstream_str_set_remove (bgpstream_str_set_t *set, char *val)
Remove a string from the set.
int bgpstream_str_set_exists (bgpstream_str_set_t *set, char *val)
Check whether a string exists in the set.
int bgpstream_str_set_size (bgpstream_str_set_t *set)
Returns the number of unique strings in the set.
int bgpstream_str_set_merge (bgpstream_str_set_t *dst_set, bgpstream_str_set_t *src_set)
Merge two string sets.
void bgpstream_str_set_clear (bgpstream_str_set_t *set)
Empty the string set.
void bgpstream_str_set_destroy (bgpstream_str_set_t *set)
Destroy the given string set.
Detailed Description
Header file that exposes the public interface of the BGP Stream String Set.
Author
Chiara Orsini
Definition in file bgpstream_utils_str_set.h.
Typedef Documentation
typedef struct bgpstream_str_set_t bgpstream_str_set_t
Opaque structure containing a string set instance.
Definition at line 43 of file bgpstream_utils_str_set.h.
Function Documentation
void bgpstream_str_set_clear (bgpstream_str_set_t * set)
Empty the string set.
Parameters
set pointer to the string set to empty
Definition at line 131 of file bgpstream_utils_str_set.c.
bgpstream_str_set_t* bgpstream_str_set_create ()
Create a new string set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 45 of file bgpstream_utils_str_set.c.
References bgpstream_str_set_destroy().
void bgpstream_str_set_destroy (bgpstream_str_set_t * set)
Destroy the given string set.
Parameters
set pointer to the string set to destroy
Definition at line 144 of file bgpstream_utils_str_set.c.
Referenced by bgpstream_str_set_create().
int bgpstream_str_set_exists (bgpstream_str_set_t * set, char * val)
Check whether a string exists in the set.
Parameters
set pointer to the string set
val the string to check
Returns
0 if the string is not in the set, 1 if it is in the set
Definition at line 98 of file bgpstream_utils_str_set.c.
int bgpstream_str_set_insert (bgpstream_str_set_t * set, char * val)
Insert a new string into the string set.
Parameters
set pointer to the string set
val the string to insert
Returns
1 if a string has been inserted, 0 if it already existed, -1 if an error occurred
Note
this function copies the provided string
Definition at line 64 of file bgpstream_utils_str_set.c.
Referenced by bgpstream_str_set_merge().
int bgpstream_str_set_merge (bgpstream_str_set_t * dst_set, bgpstream_str_set_t * src_set)
Merge two string sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 113 of file bgpstream_utils_str_set.c.
References bgpstream_str_set_insert().
int bgpstream_str_set_remove (bgpstream_str_set_t * set, char * val)
Remove a string from the set.
Parameters
set pointer to the string set
val pointer to the string to remove
Returns
1 if the string was removed, 0 if the string was not in the set
Definition at line 84 of file bgpstream_utils_str_set.c.
int bgpstream_str_set_size (bgpstream_str_set_t * set)
Returns the number of unique strings in the set.
Parameters
set pointer to the string set
Returns
the size of the string set
Definition at line 108 of file bgpstream_utils_str_set.c.