bgpstream_elem.h File Reference
Header file that exposes the public interface of a bgpstream elem.
Data Structures
struct struct_bgpstream_elem_t
A BGP Stream Elem object.
Typedefs
Public Data Structures
typedef struct
struct_bgpstream_elem_t bgpstream_elem_t
A BGP Stream Elem object.
Enumerations
Public Enums
enum bgpstream_elem_peerstate_t {
BGPSTREAM_ELEM_PEERSTATE_UNKNOWN = 0, BGPSTREAM_ELEM_PEERSTATE_IDLE = 1, BGPSTREAM_ELEM_PEERSTATE_CONNECT = 2, BGPSTREAM_ELEM_PEERSTATE_ACTIVE = 3,
BGPSTREAM_ELEM_PEERSTATE_OPENSENT = 4, BGPSTREAM_ELEM_PEERSTATE_OPENCONFIRM = 5, BGPSTREAM_ELEM_PEERSTATE_ESTABLISHED = 6, BGPSTREAM_ELEM_PEERSTATE_CLEARING = 7,
BGPSTREAM_ELEM_PEERSTATE_DELETED = 8
}
Peer state encodes the state of the peer:
enum bgpstream_elem_type_t {
BGPSTREAM_ELEM_TYPE_UNKNOWN = 0, BGPSTREAM_ELEM_TYPE_RIB = 1, BGPSTREAM_ELEM_TYPE_ANNOUNCEMENT = 2, BGPSTREAM_ELEM_TYPE_WITHDRAWAL = 3,
BGPSTREAM_ELEM_TYPE_PEERSTATE = 4
}
Elem types.
Functions
Public API Functions
bgpstream_elem_t * bgpstream_elem_create ()
Create a new BGP Stream Elem instance.
void bgpstream_elem_destroy (bgpstream_elem_t *elem)
Destroy the given BGP Stream Elem instance.
void bgpstream_elem_clear (bgpstream_elem_t *elem)
Clear the given BGP Stream Elem instance.
bgpstream_elem_t * bgpstream_elem_copy (bgpstream_elem_t *dst, bgpstream_elem_t *src)
Copy the given BGP Stream Elem to the given destination.
int bgpstream_elem_type_snprintf (char *buf, size_t len, bgpstream_elem_type_t type)
Write the string representation of the elem type into the provided buffer.
int bgpstream_elem_peerstate_snprintf (char *buf, size_t len, bgpstream_elem_peerstate_t state)
Write the string representation of the elem peerstate into the provided buffer.
char * bgpstream_elem_snprintf (char *buf, size_t len, bgpstream_elem_t *elem)
Write the string representation of the elem into the provided buffer.
Detailed Description
Header file that exposes the public interface of a bgpstream elem.
Author
Chiara Orsini
Definition in file bgpstream_elem.h.
Typedef Documentation
typedef struct struct_bgpstream_elem_t bgpstream_elem_t
A BGP Stream Elem object.
Enumeration Type Documentation
enum bgpstream_elem_peerstate_t
Peer state encodes the state of the peer:
0 - the state of the peer is unknown
[1-6] - the state encoded is one of the six FSM states described in RFC1771
[7-8] - inactive state in which all routes are cleared, more infor in quagga documentation http://goo.gl/NS9mSv
Enumerator
BGPSTREAM_ELEM_PEERSTATE_UNKNOWN
Peer state unknown.
BGPSTREAM_ELEM_PEERSTATE_IDLE
Peer state idle.
BGPSTREAM_ELEM_PEERSTATE_CONNECT
Peer state connect.
BGPSTREAM_ELEM_PEERSTATE_ACTIVE
Peer state active.
BGPSTREAM_ELEM_PEERSTATE_OPENSENT
Peer state open-sent.
BGPSTREAM_ELEM_PEERSTATE_OPENCONFIRM
Peer state open-confirm.
BGPSTREAM_ELEM_PEERSTATE_ESTABLISHED
Peer state established.
BGPSTREAM_ELEM_PEERSTATE_CLEARING
Peer state clearing.
BGPSTREAM_ELEM_PEERSTATE_DELETED
Peer state clearing.
Definition at line 56 of file bgpstream_elem.h.
enum bgpstream_elem_type_t
Elem types.
Enumerator
BGPSTREAM_ELEM_TYPE_UNKNOWN
Unknown.
BGPSTREAM_ELEM_TYPE_RIB
RIB Entry.
BGPSTREAM_ELEM_TYPE_ANNOUNCEMENT
Announcement.
BGPSTREAM_ELEM_TYPE_WITHDRAWAL
Withdrawal.
BGPSTREAM_ELEM_TYPE_PEERSTATE
Peer state change.
Definition at line 89 of file bgpstream_elem.h.
Function Documentation
void bgpstream_elem_clear (bgpstream_elem_t * elem)
Clear the given BGP Stream Elem instance.
Parameters
elem pointer to a BGP Stream Elem instance to clear
Definition at line 75 of file bgpstream_elem.c.
References struct_bgpstream_elem_t::aspath, and bgpstream_as_path_clear().
bgpstream_elem_t* bgpstream_elem_copy (bgpstream_elem_t * dst, bgpstream_elem_t * src)
Copy the given BGP Stream Elem to the given destination.
Parameters
dst pointer to an elem to copy into
src pointer to an elem to copy from
Returns
pointer to dst if successful, NULL otherwise
The dst elem must have been created using bgpstream_elem_create, or if being re-used, cleared using bgpstream_elem_clear before calling this function.
Definition at line 79 of file bgpstream_elem.c.
References struct_bgpstream_elem_t::aspath, and bgpstream_as_path_copy().
bgpstream_elem_t* bgpstream_elem_create ()
Create a new BGP Stream Elem instance.
Returns
a pointer to an Elem instance if successful, NULL otherwise
Definition at line 45 of file bgpstream_elem.c.
References struct_bgpstream_elem_t::aspath, bgpstream_as_path_create(), and malloc_zero().
void bgpstream_elem_destroy (bgpstream_elem_t * elem)
Destroy the given BGP Stream Elem instance.
Parameters
elem pointer to a BGP Stream Elem instance to destroy
Definition at line 63 of file bgpstream_elem.c.
References struct_bgpstream_elem_t::aspath, and bgpstream_as_path_destroy().
Referenced by bgpstream_elem_generator_destroy().
int bgpstream_elem_peerstate_snprintf (char * buf, size_t len, bgpstream_elem_peerstate_t state)
Write the string representation of the elem peerstate into the provided buffer.
Parameters
buf pointer to a char array
len length of the char array
state BGP Stream Elem peerstate to convert to string
Returns
the number of characters that would have been written if len was unlimited
Definition at line 138 of file bgpstream_elem.c.
References BGPSTREAM_ELEM_PEERSTATE_ACTIVE, BGPSTREAM_ELEM_PEERSTATE_CLEARING, BGPSTREAM_ELEM_PEERSTATE_CONNECT, BGPSTREAM_ELEM_PEERSTATE_DELETED, BGPSTREAM_ELEM_PEERSTATE_ESTABLISHED, BGPSTREAM_ELEM_PEERSTATE_IDLE, BGPSTREAM_ELEM_PEERSTATE_OPENCONFIRM, and BGPSTREAM_ELEM_PEERSTATE_OPENSENT.
Referenced by bgpstream_elem_snprintf().
char* bgpstream_elem_snprintf (char * buf, size_t len, bgpstream_elem_t * elem)
Write the string representation of the elem into the provided buffer.
Parameters
buf pointer to a char array
len length of the char array
elem pointer to a BGP Stream Elem to convert to string
Returns
pointer to the start of the buffer if successful, NULL otherwise
Definition at line 226 of file bgpstream_elem.c.
References struct_bgpstream_elem_t::aspath, bgpstream_addr_ntop, bgpstream_as_path_get_origin_seg(), bgpstream_as_path_seg_snprintf(), bgpstream_as_path_snprintf(), bgpstream_elem_peerstate_snprintf(), BGPSTREAM_ELEM_TYPE_ANNOUNCEMENT, BGPSTREAM_ELEM_TYPE_PEERSTATE, BGPSTREAM_ELEM_TYPE_RIB, bgpstream_elem_type_snprintf(), BGPSTREAM_ELEM_TYPE_WITHDRAWAL, bgpstream_pfx_snprintf(), struct_bgpstream_elem_t::new_state, struct_bgpstream_elem_t::nexthop, struct_bgpstream_elem_t::old_state, struct_bgpstream_elem_t::peer_address, struct_bgpstream_elem_t::peer_asnumber, struct_bgpstream_elem_t::prefix, struct_bgpstream_elem_t::timestamp, and struct_bgpstream_elem_t::type.
int bgpstream_elem_type_snprintf (char * buf, size_t len, bgpstream_elem_type_t type)
Write the string representation of the elem type into the provided buffer.
Parameters
buf pointer to a char array
len length of the char array
type BGP Stream Elem type to convert to string
Returns
the number of characters that would have been written if len was unlimited
Definition at line 100 of file bgpstream_elem.c.
References BGPSTREAM_ELEM_TYPE_ANNOUNCEMENT, BGPSTREAM_ELEM_TYPE_PEERSTATE, BGPSTREAM_ELEM_TYPE_RIB, and BGPSTREAM_ELEM_TYPE_WITHDRAWAL.
Referenced by bgpstream_elem_snprintf().