bgpstream_utils_as_path.h File Reference
Header file that exposes the public interface of BGP Stream AS objects.
Data Structures
struct bgpstream_as_path_seg
Generic AS Path Segment.
struct bgpstream_as_path_seg_asn
Simple ASN AS Path Segment.
struct bgpstream_as_path_seg_set
AS Path Segment Set.
struct bgpstream_as_path_iter
Path iterator structure.
Typedefs
Public Opaque Data Structures
typedef struct bgpstream_as_path bgpstream_as_path_t
Opaque pointer to an AS Path object.
Enumerations
Public Enums
enum bgpstream_as_path_seg_type_t {
BGPSTREAM_AS_PATH_SEG_INVALID = 0, BGPSTREAM_AS_PATH_SEG_ASN = 1, BGPSTREAM_AS_PATH_SEG_SET = 2, BGPSTREAM_AS_PATH_SEG_CONFED_SET = 3,
BGPSTREAM_AS_PATH_SEG_CONFED_SEQ = 4
}
The type of an segment.
Functions
Public API Functions
int bgpstream_as_path_seg_snprintf (char *buf, size_t len, bgpstream_as_path_seg_t *seg)
Write the string representation of the given AS Path Segment into the given character buffer.
bgpstream_as_path_seg_t * bgpstream_as_path_seg_dup (bgpstream_as_path_seg_t *src)
Duplicate the given AS Path Segment.
void bgpstream_as_path_seg_destroy (bgpstream_as_path_seg_t *seg)
Destroy the given AS Path Segment.
bgpstream_as_path_seg_hash (bgpstream_as_path_seg_t *seg)
Hash the given AS path segment into a 32bit number.
int bgpstream_as_path_seg_equal (bgpstream_as_path_seg_t *seg1, bgpstream_as_path_seg_t *seg2)
Compare two AS path segments for equality.
int bgpstream_as_path_snprintf (char *buf, size_t len, bgpstream_as_path_t *as_path)
Write the string representation of the given AS path into the given character buffer.
bgpstream_as_path_t * bgpstream_as_path_create ()
Create an empty AS path structure.
void bgpstream_as_path_clear (bgpstream_as_path_t *path)
Clear the given AS path structure.
void bgpstream_as_path_destroy (bgpstream_as_path_t *path)
Destroy the given AS path structure.
int bgpstream_as_path_copy (bgpstream_as_path_t *dst, bgpstream_as_path_t *src)
Copy one AS Path structure into another.
bgpstream_as_path_seg_t * bgpstream_as_path_get_origin_seg (bgpstream_as_path_t *path)
Get the origin AS segment from the given path.
void bgpstream_as_path_iter_reset (bgpstream_as_path_iter_t *iter)
Reset the segment iterator for the given path.
bgpstream_as_path_seg_t * bgpstream_as_path_get_next_seg (bgpstream_as_path_t *path, bgpstream_as_path_iter_t *iter)
Get the next segment from the given path.
int bgpstream_as_path_get_len (bgpstream_as_path_t *path)
Get the number of segments in the AS Path.
uint16_t bgpstream_as_path_get_data (bgpstream_as_path_t *path, uint8_t **data)
Provides access to the internal byte array that stores the path segments.
int bgpstream_as_path_populate_from_data (bgpstream_as_path_t *path, uint8_t *data, uint16_t data_len)
Populate the given AS Path from the given byte array.
int bgpstream_as_path_populate_from_data_zc (bgpstream_as_path_t *path, uint8_t *data, uint16_t data_len)
Populate the given AS Path from the given byte array (Zero Copy)
bgpstream_as_path_hash (bgpstream_as_path_t *path)
Hash the given AS path into a 32bit number.
int bgpstream_as_path_equal (bgpstream_as_path_t *path1, bgpstream_as_path_t *path2)
Compare two AS path for equality.
Variables
uint8_t type
Type of the AS Path Segment: BGPSTREAM_AS_PATH_SEG_ASN.
uint32_t asn
ASN value for this segment.
uint8_t asn_cnt
Number of ASNs in the set.
Public Data Structures
typedef struct
bgpstream_as_path_seg bgpstream_as_path_seg_t
Generic AS Path Segment.
typedef struct
bgpstream_as_path_iter bgpstream_as_path_iter_t
Path iterator structure.
struct bgpstream_as_path_seg_asn __attribute__ ((packed)) bgpstream_as_path_seg_asn_t
Simple ASN AS Path Segment.
Detailed Description
Header file that exposes the public interface of BGP Stream AS objects.
Author
Chiara Orsini, Alistair King
Definition in file bgpstream_utils_as_path.h.
Typedef Documentation
typedef struct bgpstream_as_path_iter bgpstream_as_path_iter_t
Path iterator structure.
typedef struct bgpstream_as_path_seg bgpstream_as_path_seg_t
Generic AS Path Segment.
This must be cast to the appropriate structure based on the type
typedef struct bgpstream_as_path bgpstream_as_path_t
Opaque pointer to an AS Path object.
Definition at line 83 of file bgpstream_utils_as_path.h.
Enumeration Type Documentation
enum bgpstream_as_path_seg_type_t
The type of an segment.
Enumerator
BGPSTREAM_AS_PATH_SEG_INVALID
Invalid Segment Type.
BGPSTREAM_AS_PATH_SEG_ASN
Simple ASN AS Path Segment.
BGPSTREAM_AS_PATH_SEG_SET
AS Path Segment Set.
BGPSTREAM_AS_PATH_SEG_CONFED_SET
AS Path Segment Confederation Set.
BGPSTREAM_AS_PATH_SEG_CONFED_SEQ
AS Path Segment Confederation Sequence.
Definition at line 54 of file bgpstream_utils_as_path.h.
Function Documentation
struct bgpstream_as_path_seg_set __attribute__ ((packed))
Simple ASN AS Path Segment.
AS Path Segment Set.
Simple ASN AS Path Segment.
The total number of paths in the store
The currently iterated pathset
The current path within the current pathset
Definition at line 59 of file bgpstream_utils_as_path_store.c.
void bgpstream_as_path_clear (bgpstream_as_path_t * path)
Clear the given AS path structure.
Parameters
pointer to the AS path to clear
Definition at line 286 of file bgpstream_utils_as_path.c.
References bgpstream_as_path::seg_cnt.
Referenced by bgpstream_as_path_destroy(), bgpstream_as_path_populate(), bgpstream_as_path_populate_from_data(), bgpstream_as_path_populate_from_data_zc(), bgpstream_as_path_store_path_get_path(), and bgpstream_elem_clear().
int bgpstream_as_path_copy (bgpstream_as_path_t * dst, bgpstream_as_path_t * src)
Copy one AS Path structure into another.
Parameters
dst pointer to the AS path structure to copy into
src pointer to the AS path structure to copy from
Returns
0 if the copy was successful, -1 otherwise
Note
this function will overwrite any data currently in dst. If there are existing borrowed segment pointers into the path they will become garbage.
Definition at line 305 of file bgpstream_utils_as_path.c.
References bgpstream_as_path::seg_cnt.
Referenced by bgpstream_as_path_store_path_get_path(), and bgpstream_elem_copy().
bgpstream_as_path_t* bgpstream_as_path_create ()
Create an empty AS path structure.
Returns
pointer to the created AS path object if successful, NULL otherwise
Definition at line 272 of file bgpstream_utils_as_path.c.
References malloc_zero().
Referenced by bgpstream_as_path_store_path_get_path(), and bgpstream_elem_create().
void bgpstream_as_path_destroy (bgpstream_as_path_t * path)
Destroy the given AS path structure.
Parameters
path pointer to the AS path structure to destroy
Definition at line 293 of file bgpstream_utils_as_path.c.
References bgpstream_as_path_clear().
Referenced by bgpstream_as_path_store_path_get_path(), and bgpstream_elem_destroy().
int bgpstream_as_path_equal (bgpstream_as_path_t * path1, bgpstream_as_path_t * path2) inline
Compare two AS path for equality.
Parameters
path1 pointer to the first AS path to compare
path2 pointer to the second AS path to compare
Returns
0 if the paths are not equal, non-zero if they are equal
Note
for this function to return true, the paths must be identical. If ASN ordering within sets is not consistent, this will return false.
Definition at line 566 of file bgpstream_utils_as_path.c.
uint16_t bgpstream_as_path_get_data (bgpstream_as_path_t * path, uint8_t ** data)
Provides access to the internal byte array that stores the path segments.
Parameters
path pointer to the path
[out] data set to point to the path's internal byte array
Returns
the number of bytes in the data array
This function is to be used when serializing a path. The returned data array belongs to the path and must not be modified or freed.
Definition at line 466 of file bgpstream_utils_as_path.c.
int bgpstream_as_path_get_len (bgpstream_as_path_t * path)
Get the number of segments in the AS Path.
Parameters
path pointer to the path to get the length of
Returns
the number of segments in the given path
Note
that this returns the number of BGPStream segments. This may not be the same as the number of segments in the original MRT message as BGPStream expands AS_SEQUENCE segments into a series of individual ASN segments.
Definition at line 461 of file bgpstream_utils_as_path.c.
References bgpstream_as_path::seg_cnt.
bgpstream_as_path_seg_t* bgpstream_as_path_get_next_seg (bgpstream_as_path_t * path, bgpstream_as_path_iter_t * iter)
Get the next segment from the given path.
Parameters
path pointer to the AS path to get the segment from
iter pointer to an AS path iterator
Returns
borrowed pointer to the next segment, NULL if the path has no more segments
Note
the returned pointer is owned by the path. It MUST NOT be destroyed using bgpstream_as_path_seg_destroy. Also, it is only valid as long as the path is valid.
Definition at line 438 of file bgpstream_utils_as_path.c.
References BGPSTREAM_AS_PATH_SEG_INVALID, and bgpstream_as_path_seg::type.
Referenced by bgpstream_as_path_snprintf(), bgpstream_as_path_store_path_get_next_seg(), and bgpstream_as_path_update_fields().
bgpstream_as_path_seg_t* bgpstream_as_path_get_origin_seg (bgpstream_as_path_t * path)
Get the origin AS segment from the given path.
Parameters
path pointer to the AS path to extract the origin AS for
Returns
borrowed pointer to the origin AS segment
Note
the returned pointer is owned by the path. It MUST NOT be destroyed using bgpstream_as_path_seg_destroy. Also, it is only valid as long as the path is valid.
Definition at line 417 of file bgpstream_utils_as_path.c.
Referenced by bgpstream_elem_snprintf().
bgpstream_as_path_hash (bgpstream_as_path_t * path)
Hash the given AS path into a 32bit number.
Parameters
path pointer to the AS path to hash
Returns
32bit hash of the AS path
Definition at line 544 of file bgpstream_utils_as_path.c.
References bgpstream_as_path_seg_hash().
void bgpstream_as_path_iter_reset (bgpstream_as_path_iter_t * iter)
Reset the segment iterator for the given path.
Parameters
iter pointer to the AS path iterator to reset
Definition at line 432 of file bgpstream_utils_as_path.c.
Referenced by bgpstream_as_path_populate(), bgpstream_as_path_snprintf(), bgpstream_as_path_store_path_get_next_seg(), bgpstream_as_path_store_path_iter_reset(), and bgpstream_as_path_update_fields().
int bgpstream_as_path_populate_from_data (bgpstream_as_path_t * path, uint8_t * data, uint16_t data_len)
Populate the given AS Path from the given byte array.
Parameters
path pointer to the path to populate
data pointer to the data arrayg
data_len number of bytes in the data array
Returns
0 if the path was populated successfully, -1 otherwise
Definition at line 481 of file bgpstream_utils_as_path.c.
References bgpstream_as_path_clear(), and bgpstream_as_path_update_fields().
int bgpstream_as_path_populate_from_data_zc (bgpstream_as_path_t * path, uint8_t * data, uint16_t data_len)
Populate the given AS Path from the given byte array (Zero Copy)
Parameters
path pointer to the path to populate
data pointer to the data array
data_len number of bytes in the data array
Returns
0 if the path was populated successfully, -1 otherwise
Note
this function does not copy the data into the path. The path is only valid as long as the data array passed to this function is valid.
Definition at line 512 of file bgpstream_utils_as_path.c.
References bgpstream_as_path_clear(), and bgpstream_as_path_update_fields().
Referenced by bgpstream_as_path_store_insert_path().
void bgpstream_as_path_seg_destroy (bgpstream_as_path_seg_t * seg)
Destroy the given AS Path Segment.
Parameters
seg pointer to the AS path segment to destroy
Definition at line 184 of file bgpstream_utils_as_path.c.
bgpstream_as_path_seg_t* bgpstream_as_path_seg_dup (bgpstream_as_path_seg_t * src)
Duplicate the given AS Path Segment.
Parameters
src pointer to the AS path segment to duplicate
Returns
a pointer to the created segment if successful, NULL otherwise
Note
the returned segment must be destroyed using bgpstream_as_path_seg_destroy
Definition at line 166 of file bgpstream_utils_as_path.c.
References BGPSTREAM_AS_PATH_SEG_ASN, BGPSTREAM_AS_PATH_SEG_INVALID, and bgpstream_as_path_seg::type.
int bgpstream_as_path_seg_equal (bgpstream_as_path_seg_t * seg1, bgpstream_as_path_seg_t * seg2)
Compare two AS path segments for equality.
Parameters
seg1 pointer to the first AS path segment to compare
seg2 pointer to the second AS path segment to compare
Returns
0 if the segments are not equal, non-zero if they are equal
Definition at line 211 of file bgpstream_utils_as_path.c.
References asn, asn_cnt, BGPSTREAM_AS_PATH_SEG_ASN, BGPSTREAM_AS_PATH_SEG_INVALID, and bgpstream_as_path_seg::type.
bgpstream_as_path_seg_hash (bgpstream_as_path_seg_t * seg) inline
Hash the given AS path segment into a 32bit number.
Parameters
seg pointer to the AS path segment to hash
Returns
32bit hash of the AS path segment
Definition at line 196 of file bgpstream_utils_as_path.c.
References BGPSTREAM_AS_PATH_SEG_ASN, and bgpstream_as_path_seg::type.
Referenced by bgpstream_as_path_hash().
int bgpstream_as_path_seg_snprintf (char * buf, size_t len, bgpstream_as_path_seg_t * seg)
Write the string representation of the given AS Path Segment into the given character buffer.
Parameters
buf pointer to a character buffer at least len bytes long
len length of the given character buffer
seg pointer to the segment to convert to string
Returns
the number of characters written given an infinite len (not including the trailing nul). If this value is greater than or equal to len, then the output was truncated.
Definition at line 115 of file bgpstream_utils_as_path.c.
References asn, BGPSTREAM_AS_PATH_SEG_ASN, BGPSTREAM_AS_PATH_SEG_CONFED_SEQ, BGPSTREAM_AS_PATH_SEG_CONFED_SET, BGPSTREAM_AS_PATH_SEG_SET, and bgpstream_as_path_seg::type.
Referenced by bgpstream_as_path_snprintf(), and bgpstream_elem_snprintf().
int bgpstream_as_path_snprintf (char * buf, size_t len, bgpstream_as_path_t * as_path)
Write the string representation of the given AS path into the given character buffer.
Parameters
buf pointer to a character buffer at least len bytes long
len length of the given character buffer
as_path pointer to the bgpstream AS path to convert to string
Returns
the number of characters written given an infinite len (not including the trailing nul). If this value is greater than or equal to len, then the output was truncated.
Definition at line 242 of file bgpstream_utils_as_path.c.
References bgpstream_as_path_get_next_seg(), bgpstream_as_path_iter_reset(), and bgpstream_as_path_seg_snprintf().
Referenced by bgpstream_as_path_populate(), and bgpstream_elem_snprintf().
Variable Documentation
uint32_t asn
ASN value for this segment.
Array of ASNs in the set.
Definition at line 829 of file bgpstream_utils_as_path.h.
Referenced by bgpstream_as_path_populate(), bgpstream_as_path_seg_equal(), and bgpstream_as_path_seg_snprintf().
uint8_t asn_cnt
Number of ASNs in the set.
Definition at line 833 of file bgpstream_utils_as_path.h.
Referenced by bgpstream_as_path_seg_equal().
uint8_t type
Type of the AS Path Segment: BGPSTREAM_AS_PATH_SEG_ASN.
Type of the AS Path Segment: BGPSTREAM_AS_PATH_SEG_SET, BGPSTREAM_AS_PATH_SEG_CONFED_SET, BGPSTREAM_AS_PATH_SEG_CONFED_SEQ.
Definition at line 826 of file bgpstream_utils_as_path.h.