bgpstream_utils_peer_sig_map.h File Reference
< for COLLECTOR_NAME_LEN
Data Structures
struct struct_bgpstream_peer_sig_t
Structure that uniquely identifies a single peer.
Typedefs
Opaque Data Structures
typedef uint16_t bgpstream_peer_id_t
Type of a peer ID.
typedef struct
bgpstream_peer_sig_map bgpstream_peer_sig_map_t
Opaque structure containing a peer signature map instance.
Public Data Structures
typedef struct
struct_bgpstream_peer_sig_t bgpstream_peer_sig_t
Structure that uniquely identifies a single peer.
Functions
Public API Functions
bgpstream_peer_sig_map_t * bgpstream_peer_sig_map_create ()
Create a new peer signature map.
bgpstream_peer_id_t bgpstream_peer_sig_map_get_id (bgpstream_peer_sig_map_t *map, char *collector_str, bgpstream_ip_addr_t *peer_ip_addr, uint32_t peer_asnumber)
Get (or set and get) the peer ID for the given peer signature.
bgpstream_peer_sig_t * bgpstream_peer_sig_map_get_sig (bgpstream_peer_sig_map_t *map, bgpstream_peer_id_t peer_id)
Get the peer signature for the given peer ID.
int bgpstream_peer_sig_map_get_size (bgpstream_peer_sig_map_t *map)
Get the number of peer signatures in the given map.
void bgpstream_peer_sig_map_destroy (bgpstream_peer_sig_map_t *map)
Destroy the given peer signature map.
void bgpstream_peer_sig_map_clear (bgpstream_peer_sig_map_t *map)
Empty the given peer signature map.
Detailed Description
< for COLLECTOR_NAME_LEN
Header file that exposes the public interface of the BGP Stream Peer Signature Map.
Author
Chiara Orsini
Definition in file bgpstream_utils_peer_sig_map.h.
Typedef Documentation
typedef uint16_t bgpstream_peer_id_t
Type of a peer ID.
Definition at line 46 of file bgpstream_utils_peer_sig_map.h.
typedef struct bgpstream_peer_sig_map bgpstream_peer_sig_map_t
Opaque structure containing a peer signature map instance.
Definition at line 49 of file bgpstream_utils_peer_sig_map.h.
typedef struct struct_bgpstream_peer_sig_t bgpstream_peer_sig_t
Structure that uniquely identifies a single peer.
Function Documentation
void bgpstream_peer_sig_map_clear (bgpstream_peer_sig_map_t * map)
Empty the given peer signature map.
Parameters
map peer sig map
Definition at line 252 of file bgpstream_utils_peer_sig_map.c.
bgpstream_peer_sig_map_t* bgpstream_peer_sig_map_create ()
Create a new peer signature map.
Returns
a pointer to the created peer sig map if successful, NULL otherwise.
Definition at line 149 of file bgpstream_utils_peer_sig_map.c.
References bgpstream_peer_sig_map_destroy(), and malloc_zero().
void bgpstream_peer_sig_map_destroy (bgpstream_peer_sig_map_t * map)
Destroy the given peer signature map.
Parameters
map pointer to the peer sig map to destroy
Definition at line 232 of file bgpstream_utils_peer_sig_map.c.
Referenced by bgpstream_peer_sig_map_create().
bgpstream_peer_id_t bgpstream_peer_sig_map_get_id (bgpstream_peer_sig_map_t * map, char * collector_str, bgpstream_ip_addr_t * peer_ip_addr, uint32_t peer_asnumber)
Get (or set and get) the peer ID for the given peer signature.
Parameters
map pointer to the peer sig map to query
collector_str string name of the collector
peer_ip_addr pointer to the IP address of the peer
peer_asnumber AS number of the peer
Returns
the peer ID for this peer signature, 0 if an error occurred
Definition at line 176 of file bgpstream_utils_peer_sig_map.c.
References BGPSTREAM_ADDR_VERSION_IPV4, BGPSTREAM_ADDR_VERSION_IPV6, struct_bgpstream_peer_sig_t::collector_str, struct_bgpstream_addr_storage_t::ipv4, struct_bgpstream_addr_storage_t::ipv6, struct_bgpstream_peer_sig_t::peer_asnumber, struct_bgpstream_peer_sig_t::peer_ip_addr, struct_bgpstream_ip_addr_t::version, and struct_bgpstream_addr_storage_t::version.
bgpstream_peer_sig_t* bgpstream_peer_sig_map_get_sig (bgpstream_peer_sig_map_t * map, bgpstream_peer_id_t peer_id)
Get the peer signature for the given peer ID.
Parameters
map pointer to the peer sig map to query
peer_id peer ID to retrieve signature for
Returns
pointer to the peer signature for the given peer ID, NULL if it was not found
Definition at line 212 of file bgpstream_utils_peer_sig_map.c.
int bgpstream_peer_sig_map_get_size (bgpstream_peer_sig_map_t * map)
Get the number of peer signatures in the given map.
Parameters
map pointer to the peer sig map to find the size of
Returns
the number of peer signatures in the given map
Definition at line 226 of file bgpstream_utils_peer_sig_map.c.