bgpstream_record.h File Reference
Header file that exposes the public interface of a bgpstream record.
Data Structures
struct struct_bgpstream_record_attributes_t
Record attributes.
struct struct_bgpstream_record_t
Record structure.
Typedefs
Public Opaque Data Structures
typedef struct struct_BGPDUMP_ENTRY bgpstream_record_mrt_data_t
An opaque pointer to a BGPDUMP_ENTRY field.
Public Data Structures
typedef struct
struct_bgpstream_record_attributes_t bgpstream_record_attributes_t
Record attributes.
typedef struct
struct_bgpstream_record_t bgpstream_record_t
Record structure.
Enumerations
Public Enums
enum bgpstream_record_dump_type_t { BGPSTREAM_UPDATE = 0, BGPSTREAM_RIB = 1 }
The type of the record.
enum bgpstream_dump_position_t { BGPSTREAM_DUMP_START = 0, BGPSTREAM_DUMP_MIDDLE = 1, BGPSTREAM_DUMP_END = 2 }
The position of this record in the dump.
enum bgpstream_record_status_t {
BGPSTREAM_RECORD_STATUS_VALID_RECORD = 0, BGPSTREAM_RECORD_STATUS_FILTERED_SOURCE = 1, BGPSTREAM_RECORD_STATUS_EMPTY_SOURCE = 2, BGPSTREAM_RECORD_STATUS_CORRUPTED_SOURCE = 3,
BGPSTREAM_RECORD_STATUS_CORRUPTED_RECORD = 4
}
Status of the record.
Functions
Public API Functions
bgpstream_record_t * bgpstream_record_create ()
Create a new BGP Stream Record instance for passing to bgpstream_get_next_record.
void bgpstream_record_destroy (bgpstream_record_t *record)
Destroy the given BGP Stream Record instance.
void bgpstream_record_clear (bgpstream_record_t *record)
Clear the given BGP Stream Record instance.
bgpstream_elem_t * bgpstream_record_get_next_elem (bgpstream_record_t *record)
Retrieve the next elem from the record.
void bgpstream_record_print_mrt_data (bgpstream_record_t *const bs_record)
Dump the given record to stdout in bgpdump format.
Detailed Description
Header file that exposes the public interface of a bgpstream record.
Author
Chiara Orsini
Definition in file bgpstream_record.h.
Typedef Documentation
typedef struct struct_bgpstream_record_attributes_t bgpstream_record_attributes_t
Record attributes.
typedef struct struct_BGPDUMP_ENTRY bgpstream_record_mrt_data_t
An opaque pointer to a BGPDUMP_ENTRY field.
Note
this is an internal data structure, it is not guaranteed that it will continue to conform to the public BGPDUMP_ENTRY structure. This is NOT for use in user code
Definition at line 49 of file bgpstream_record.h.
typedef struct struct_bgpstream_record_t bgpstream_record_t
Record structure.
Enumeration Type Documentation
enum bgpstream_dump_position_t
The position of this record in the dump.
Enumerator
BGPSTREAM_DUMP_START
This is the first record of the dump.
BGPSTREAM_DUMP_MIDDLE
This is a record in the middle of the dump.
i.e. not the first or the last record of the dump
BGPSTREAM_DUMP_END
This is the last record of the dump.
Definition at line 77 of file bgpstream_record.h.
enum bgpstream_record_dump_type_t
The type of the record.
Enumerator
BGPSTREAM_UPDATE
The record contains data for a BGP Update message.
BGPSTREAM_RIB
The record contains data for a BGP RIB message.
Definition at line 66 of file bgpstream_record.h.
enum bgpstream_record_status_t
Status of the record.
Enumerator
BGPSTREAM_RECORD_STATUS_VALID_RECORD
The record is valid and may be used.
BGPSTREAM_RECORD_STATUS_FILTERED_SOURCE
Source is not empty, but no valid record was found.
BGPSTREAM_RECORD_STATUS_EMPTY_SOURCE
Source has no entries.
Definition at line 92 of file bgpstream_record.h.
Function Documentation
void bgpstream_record_clear (bgpstream_record_t * record)
Clear the given BGP Stream Record instance.
Parameters
record pointer to a BGP Stream Record instance to clear
Note
the record passed to bgpstream_get_next_record is automatically cleaned.
Definition at line 79 of file bgpstream_record.c.
References struct_bgpstream_record_t::attributes, struct_bgpstream_record_t::bd_entry, BGPSTREAM_DUMP_START, bgpstream_elem_generator_clear(), BGPSTREAM_RECORD_STATUS_EMPTY_SOURCE, BGPSTREAM_UPDATE, struct_bgpstream_record_attributes_t::dump_collector, struct_bgpstream_record_t::dump_pos, struct_bgpstream_record_attributes_t::dump_project, struct_bgpstream_record_attributes_t::dump_time, struct_bgpstream_record_attributes_t::dump_type, struct_bgpstream_record_t::elem_generator, struct_bgpstream_record_attributes_t::record_time, and struct_bgpstream_record_t::status.
Referenced by bgpstream_get_next_record(), and bgpstream_record_create().
bgpstream_record_t* bgpstream_record_create ()
Create a new BGP Stream Record instance for passing to bgpstream_get_next_record.
Returns
a pointer to a Record instance if successful, NULL otherwise
A Record may be reused for successive calls to bgpstream_get_next_record if records are processed independently of each other
Definition at line 35 of file bgpstream_record.c.
References struct_bgpstream_record_t::bd_entry, bgpstream_elem_generator_create(), bgpstream_record_clear(), bgpstream_record_destroy(), and struct_bgpstream_record_t::elem_generator.
void bgpstream_record_destroy (bgpstream_record_t * record)
Destroy the given BGP Stream Record instance.
Parameters
record pointer to a BGP Stream Record instance to destroy
Definition at line 57 of file bgpstream_record.c.
References struct_bgpstream_record_t::bd_entry, bgpstream_elem_generator_destroy(), and struct_bgpstream_record_t::elem_generator.
Referenced by bgpstream_record_create().
bgpstream_elem_t* bgpstream_record_get_next_elem (bgpstream_record_t * record)
Retrieve the next elem from the record.
Parameters
record pointer to the BGP Stream Record to retrieve the elem from
Returns
borrowed pointer to the next Elem in the record, NULL if there are no more Elems
The returned pointer is guaranteed to be valid until the record is re-used in a subsequent call to bgpstream_get_next_record, or is destroyed with bgpstream_record_destroy
Definition at line 100 of file bgpstream_record.c.
References bgpstream_elem_generator_get_next_elem(), bgpstream_elem_generator_is_populated(), bgpstream_elem_generator_populate(), and struct_bgpstream_record_t::elem_generator.
void bgpstream_record_print_mrt_data (bgpstream_record_t *const bs_record)
Dump the given record to stdout in bgpdump format.
Parameters
record pointer to a BGP Stream Record instance to dump
See https://bitbucket.org/ripencc/bgpdump for more information about bgpdump
Definition at line 96 of file bgpstream_record.c.
References struct_bgpstream_record_t::bd_entry.