bgpstream_utils_pfx_set.h File Reference
Header file that exposes the public interface of the BGP Stream Prefix Sets.
Typedefs
Opaque Data Structures
typedef struct
bgpstream_pfx_storage_set bgpstream_pfx_storage_set_t
Opaque structure containing an Prefix Storage set instance.
typedef struct
bgpstream_ipv4_pfx_set bgpstream_ipv4_pfx_set_t
Opaque structure containing an IPv4 Prefix set instance.
typedef struct
bgpstream_ipv6_pfx_set bgpstream_ipv6_pfx_set_t
Opaque structure containing an IPv6 Prefix set instance.
Functions
Public API Functions
bgpstream_pfx_storage_set_t * bgpstream_pfx_storage_set_create ()
Create a new Prefix Storage set instance.
int bgpstream_pfx_storage_set_insert (bgpstream_pfx_storage_set_t *set, bgpstream_pfx_storage_t *pfx)
Insert a new prefix into the given set.
int bgpstream_pfx_storage_set_size (bgpstream_pfx_storage_set_t *set)
Get the number of prefixes in the given set.
int bgpstream_pfx_storage_set_merge (bgpstream_pfx_storage_set_t *dst_set, bgpstream_pfx_storage_set_t *src_set)
Merge two prefix sets.
void bgpstream_pfx_storage_set_destroy (bgpstream_pfx_storage_set_t *set)
Destroy the given prefix set.
void bgpstream_pfx_storage_set_clear (bgpstream_pfx_storage_set_t *set)
Empty the prefix set.
bgpstream_ipv4_pfx_set_t * bgpstream_ipv4_pfx_set_create ()
Create a new IPv4 Prefix set instance.
int bgpstream_ipv4_pfx_set_insert (bgpstream_ipv4_pfx_set_t *set, bgpstream_ipv4_pfx_t *pfx)
Insert a new prefix into the given set.
int bgpstream_ipv4_pfx_set_size (bgpstream_ipv4_pfx_set_t *set)
Get the number of prefixes in the given set.
int bgpstream_ipv4_pfx_set_merge (bgpstream_ipv4_pfx_set_t *dst_set, bgpstream_ipv4_pfx_set_t *src_set)
Merge two prefix sets.
void bgpstream_ipv4_pfx_set_destroy (bgpstream_ipv4_pfx_set_t *set)
Destroy the given prefix set.
void bgpstream_ipv4_pfx_set_clear (bgpstream_ipv4_pfx_set_t *set)
Empty the prefix set.
bgpstream_ipv6_pfx_set_t * bgpstream_ipv6_pfx_set_create ()
Create a new IPv6 Prefix set instance.
int bgpstream_ipv6_pfx_set_insert (bgpstream_ipv6_pfx_set_t *set, bgpstream_ipv6_pfx_t *pfx)
Insert a new prefix into the given set.
int bgpstream_ipv6_pfx_set_size (bgpstream_ipv6_pfx_set_t *set)
Get the number of prefixes in the given set.
int bgpstream_ipv6_pfx_set_merge (bgpstream_ipv6_pfx_set_t *dst_set, bgpstream_ipv6_pfx_set_t *src_set)
Merge two prefix sets.
void bgpstream_ipv6_pfx_set_destroy (bgpstream_ipv6_pfx_set_t *set)
Destroy the given prefix set.
void bgpstream_ipv6_pfx_set_clear (bgpstream_ipv6_pfx_set_t *set)
Empty the prefix set.
Detailed Description
Header file that exposes the public interface of the BGP Stream Prefix Sets.
There is one set for each bgpstream_pfx type (Storage, IPv4 and IPv6).
Author
Chiara Orsini
Definition in file bgpstream_utils_pfx_set.h.
Typedef Documentation
typedef struct bgpstream_ipv4_pfx_set bgpstream_ipv4_pfx_set_t
Opaque structure containing an IPv4 Prefix set instance.
Definition at line 49 of file bgpstream_utils_pfx_set.h.
typedef struct bgpstream_ipv6_pfx_set bgpstream_ipv6_pfx_set_t
Opaque structure containing an IPv6 Prefix set instance.
Definition at line 52 of file bgpstream_utils_pfx_set.h.
typedef struct bgpstream_pfx_storage_set bgpstream_pfx_storage_set_t
Opaque structure containing an Prefix Storage set instance.
Definition at line 46 of file bgpstream_utils_pfx_set.h.
Function Documentation
void bgpstream_ipv4_pfx_set_clear (bgpstream_ipv4_pfx_set_t * set)
Empty the prefix set.
Parameters
set pointer to the prefix set to clear
Definition at line 217 of file bgpstream_utils_pfx_set.c.
bgpstream_ipv4_pfx_set_t* bgpstream_ipv4_pfx_set_create ()
Create a new IPv4 Prefix set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 154 of file bgpstream_utils_pfx_set.c.
References bgpstream_ipv4_pfx_set_destroy().
void bgpstream_ipv4_pfx_set_destroy (bgpstream_ipv4_pfx_set_t * set)
Destroy the given prefix set.
Parameters
set pointer to the prefix set to destroy
Definition at line 211 of file bgpstream_utils_pfx_set.c.
Referenced by bgpstream_ipv4_pfx_set_create().
int bgpstream_ipv4_pfx_set_insert (bgpstream_ipv4_pfx_set_t * set, bgpstream_ipv4_pfx_t * pfx)
Insert a new prefix into the given set.
Parameters
set pointer to the prefix set
pfx prefix to insert in the set
Returns
1 if the prefix was inserted, 0 if it already existed, -1 if an error occurred
This function takes a copy of the prefix before it is inserted in the set.
Definition at line 174 of file bgpstream_utils_pfx_set.c.
Referenced by bgpstream_ipv4_pfx_set_merge().
int bgpstream_ipv4_pfx_set_merge (bgpstream_ipv4_pfx_set_t * dst_set, bgpstream_ipv4_pfx_set_t * src_set)
Merge two prefix sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 193 of file bgpstream_utils_pfx_set.c.
References bgpstream_ipv4_pfx_set_insert().
int bgpstream_ipv4_pfx_set_size (bgpstream_ipv4_pfx_set_t * set)
Get the number of prefixes in the given set.
Parameters
set pointer to the prefix set
Returns
the size of the prefix set
Definition at line 188 of file bgpstream_utils_pfx_set.c.
void bgpstream_ipv6_pfx_set_clear (bgpstream_ipv6_pfx_set_t * set)
Empty the prefix set.
Parameters
set pointer to the prefix set to clear
Definition at line 289 of file bgpstream_utils_pfx_set.c.
bgpstream_ipv6_pfx_set_t* bgpstream_ipv6_pfx_set_create ()
Create a new IPv6 Prefix set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 226 of file bgpstream_utils_pfx_set.c.
References bgpstream_ipv6_pfx_set_destroy().
void bgpstream_ipv6_pfx_set_destroy (bgpstream_ipv6_pfx_set_t * set)
Destroy the given prefix set.
Parameters
set pointer to the prefix set to destroy
Definition at line 283 of file bgpstream_utils_pfx_set.c.
Referenced by bgpstream_ipv6_pfx_set_create().
int bgpstream_ipv6_pfx_set_insert (bgpstream_ipv6_pfx_set_t * set, bgpstream_ipv6_pfx_t * pfx)
Insert a new prefix into the given set.
Parameters
set pointer to the prefix set
pfx prefix to insert in the set
Returns
1 if the prefix was inserted, 0 if it already existed, -1 if an error occurred
Definition at line 246 of file bgpstream_utils_pfx_set.c.
Referenced by bgpstream_ipv6_pfx_set_merge().
int bgpstream_ipv6_pfx_set_merge (bgpstream_ipv6_pfx_set_t * dst_set, bgpstream_ipv6_pfx_set_t * src_set)
Merge two prefix sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 265 of file bgpstream_utils_pfx_set.c.
References bgpstream_ipv6_pfx_set_insert().
int bgpstream_ipv6_pfx_set_size (bgpstream_ipv6_pfx_set_t * set)
Get the number of prefixes in the given set.
Parameters
set pointer to the prefix set
Returns
the size of the prefix set
Definition at line 260 of file bgpstream_utils_pfx_set.c.
void bgpstream_pfx_storage_set_clear (bgpstream_pfx_storage_set_t * set)
Empty the prefix set.
Parameters
set pointer to the prefix set to clear
Definition at line 145 of file bgpstream_utils_pfx_set.c.
bgpstream_pfx_storage_set_t* bgpstream_pfx_storage_set_create ()
Create a new Prefix Storage set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 82 of file bgpstream_utils_pfx_set.c.
References bgpstream_pfx_storage_set_destroy().
void bgpstream_pfx_storage_set_destroy (bgpstream_pfx_storage_set_t * set)
Destroy the given prefix set.
Parameters
set pointer to the prefix set to destroy
Definition at line 139 of file bgpstream_utils_pfx_set.c.
Referenced by bgpstream_pfx_storage_set_create().
int bgpstream_pfx_storage_set_insert (bgpstream_pfx_storage_set_t * set, bgpstream_pfx_storage_t * pfx)
Insert a new prefix into the given set.
Parameters
set pointer to the prefix set
pfx prefix to insert in the set
Returns
1 if the prefix was inserted, 0 if it already existed, -1 if an error occurred
Definition at line 102 of file bgpstream_utils_pfx_set.c.
Referenced by bgpstream_pfx_storage_set_merge().
int bgpstream_pfx_storage_set_merge (bgpstream_pfx_storage_set_t * dst_set, bgpstream_pfx_storage_set_t * src_set)
Merge two prefix sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 121 of file bgpstream_utils_pfx_set.c.
References bgpstream_pfx_storage_set_insert().
int bgpstream_pfx_storage_set_size (bgpstream_pfx_storage_set_t * set)
Get the number of prefixes in the given set.
Parameters
set pointer to the prefix set
Returns
the size of the prefix set
Definition at line 116 of file bgpstream_utils_pfx_set.c.