bgpstream.h File Reference
Header file that exposes the public interface of bgpstream.
Data Structures
struct struct_bgpstream_data_interface_info
Structure that contains information about a BGP Stream Data Interface.
struct struct_bgpstream_data_interface_option
Structure that represents BGP Stream Data Interface Option.
Typedefs
Public Opaque Data Structures
typedef struct struct_bgpstream_t bgpstream_t
Opaque handle that represents a BGP Stream instance.
Public Data Structures
typedef struct
struct_bgpstream_data_interface_info bgpstream_data_interface_info_t
Structure that contains information about a BGP Stream Data Interface.
typedef struct
struct_bgpstream_data_interface_option bgpstream_data_interface_option_t
Structure that represents BGP Stream Data Interface Option.
Enumerations
Public Enums
enum bgpstream_filter_type_t { BGPSTREAM_FILTER_TYPE_PROJECT = 1, BGPSTREAM_FILTER_TYPE_COLLECTOR = 2, BGPSTREAM_FILTER_TYPE_RECORD_TYPE = 3 }
The type of the filter to be applied.
enum bgpstream_data_interface_id_t {
BGPSTREAM_DATA_INTERFACE_BROKER = 1, BGPSTREAM_DATA_INTERFACE_SINGLEFILE = 2, BGPSTREAM_DATA_INTERFACE_CSVFILE = 3, BGPSTREAM_DATA_INTERFACE_MYSQL = 4,
BGPSTREAM_DATA_INTERFACE_SQLITE = 5
}
Data Interface IDs.
Functions
Public API Functions
bgpstream_t * bgpstream_create ()
Create a new BGP Stream instance.
void bgpstream_add_filter (bgpstream_t *bs, bgpstream_filter_type_t filter_type, const char *filter_value)
Add a filter in order to select a subset of the bgp data available.
void bgpstream_add_rib_period_filter (bgpstream_t *bs, uint32_t period)
Add a filter to configure the minimum bgp time interval between RIB files that belong to the same collector.
void bgpstream_add_interval_filter (bgpstream_t *bs, uint32_t begin_time, uint32_t end_time)
Add a filter to select a specific time range from the BGP data available.
int bgpstream_get_data_interfaces (bgpstream_t *bs, bgpstream_data_interface_id_t **if_ids)
Get a list of data interfaces that are currently supported.
bgpstream_data_interface_id_t bgpstream_get_data_interface_id_by_name (bgpstream_t *bs, const char *name)
Get the ID of the data interface with the given name.
bgpstream_data_interface_info_t * bgpstream_get_data_interface_info (bgpstream_t *bs, bgpstream_data_interface_id_t if_id)
Get information for the given data interface.
int bgpstream_get_data_interface_options (bgpstream_t *bs, bgpstream_data_interface_id_t if_id, bgpstream_data_interface_option_t **opts)
Get a list of valid option types for the given data interface.
bgpstream_data_interface_option_t * bgpstream_get_data_interface_option_by_name (bgpstream_t *bs, bgpstream_data_interface_id_t if_id, const char *name)
Get the data interface option for the given data interface and option name.
void bgpstream_set_data_interface_option (bgpstream_t *bs, bgpstream_data_interface_option_t *option_type, const char *option_value)
Set a data interface option.
bgpstream_data_interface_id_t bgpstream_get_data_interface_id (bgpstream_t *bs)
Get the ID of the currently active data interface.
void bgpstream_set_data_interface (bgpstream_t *bs, bgpstream_data_interface_id_t if_id)
Set the data interface that BGP Stream uses to find BGP data.
void bgpstream_set_blocking (bgpstream_t *bs)
Configure the interface to blocks waiting for new data instead of returning end-of-stream if no more data is available.
int bgpstream_start (bgpstream_t *bs)
Start the given BGP Stream instance.
int bgpstream_get_next_record (bgpstream_t *bs, bgpstream_record_t *record)
Retrieve from the stream, the next record that matches configured filters.
void bgpstream_stop (bgpstream_t *bs)
Stop the given BGP Stream instance.
void bgpstream_destroy (bgpstream_t *bs)
Destroy the given BGP Stream instance.
Detailed Description
Header file that exposes the public interface of bgpstream.
See bgpstream_record.h and bgpstream_elem.h for the public interfaces of bgpstream_record and bgpstream_elem respectively.
Author
Chiara Orsini
Definition in file bgpstream.h.
Typedef Documentation
typedef struct struct_bgpstream_data_interface_info bgpstream_data_interface_info_t
Structure that contains information about a BGP Stream Data Interface.
typedef struct struct_bgpstream_data_interface_option bgpstream_data_interface_option_t
Structure that represents BGP Stream Data Interface Option.
typedef struct struct_bgpstream_t bgpstream_t
Opaque handle that represents a BGP Stream instance.
Definition at line 47 of file bgpstream.h.
Enumeration Type Documentation
enum bgpstream_data_interface_id_t
Data Interface IDs.
Enumerator
BGPSTREAM_DATA_INTERFACE_BROKER
Broker data interface.
BGPSTREAM_DATA_INTERFACE_SINGLEFILE
Customlist interface.
BGPSTREAM_DATA_INTERFACE_CSVFILE
CSV file interface.
BGPSTREAM_DATA_INTERFACE_MYSQL
MySQL data interface.
BGPSTREAM_DATA_INTERFACE_SQLITE
SQLITE file interface.
Definition at line 72 of file bgpstream.h.
enum bgpstream_filter_type_t
The type of the filter to be applied.
Enumerator
BGPSTREAM_FILTER_TYPE_PROJECT
Filter records based on associated project (e.g.
'ris')
BGPSTREAM_FILTER_TYPE_COLLECTOR
Filter records based on collector (e.g.
'rrc01')
BGPSTREAM_FILTER_TYPE_RECORD_TYPE
Filter records based on record type (e.g.
'updates')
Definition at line 57 of file bgpstream.h.
Function Documentation
void bgpstream_add_filter (bgpstream_t * bs, bgpstream_filter_type_t filter_type, const char * filter_value)
Add a filter in order to select a subset of the bgp data available.
Parameters
bs pointer to a BGP Stream instance to filter
filter_type the type of the filter to apply
filter_value the value to set the filter to
Definition at line 289 of file bgpstream.c.
void bgpstream_add_interval_filter (bgpstream_t * bs, uint32_t begin_time, uint32_t end_time)
Add a filter to select a specific time range from the BGP data available.
Parameters
bs pointer to a BGP Stream instance to filter
begin_time the first time that will match the filter (inclusive)
end_time the last time that will match the filter (inclusive)
Definition at line 310 of file bgpstream.c.
void bgpstream_add_rib_period_filter (bgpstream_t * bs, uint32_t period)
Add a filter to configure the minimum bgp time interval between RIB files that belong to the same collector.
This information can be changed at run time.
Parameters
bs pointer to a BGP Stream instance to filter
period time period (if zero, all available RIBs are processed)
Definition at line 300 of file bgpstream.c.
bgpstream_t* bgpstream_create ()
Create a new BGP Stream instance.
Returns
a pointer to a BGP Stream instance if successful, NULL otherwise
Definition at line 241 of file bgpstream.c.
References bgpstream_destroy().
void bgpstream_destroy (bgpstream_t * bs)
Destroy the given BGP Stream instance.
Parameters
bs pointer to a BGP Stream instance to destroy
Definition at line 579 of file bgpstream.c.
Referenced by bgpstream_create().
bgpstream_data_interface_id_t bgpstream_get_data_interface_id (bgpstream_t * bs)
Get the ID of the currently active data interface.
Parameters
bs pointer to a BGP Stream instance
Returns
the ID of the currently active data interface
If no data interface has been explicitly set, this function will return the ID of the default data interface.
Definition at line 462 of file bgpstream.c.
bgpstream_data_interface_id_t bgpstream_get_data_interface_id_by_name (bgpstream_t * bs, const char * name)
Get the ID of the data interface with the given name.
Parameters
name name of the data interface to retrieve the ID for
Returns
the ID of the data interface with the given name, 0 if no matching interface was found
Definition at line 330 of file bgpstream.c.
References ARR_CNT, and struct_bgpstream_data_interface_info::id.
bgpstream_data_interface_info_t* bgpstream_get_data_interface_info (bgpstream_t * bs, bgpstream_data_interface_id_t if_id)
Get information for the given data interface.
Parameters
bs pointer to a BGP Stream instance
if_id ID of the interface to get the name for
Returns
borrowed pointer to an interface info structure
Definition at line 347 of file bgpstream.c.
bgpstream_data_interface_option_t* bgpstream_get_data_interface_option_by_name (bgpstream_t * bs, bgpstream_data_interface_id_t if_id, const char * name)
Get the data interface option for the given data interface and option name.
Parameters
bs pointer to a BGP Stream instance
if_id ID of the interface to get option info for
name name of the option to retrieve
Returns
pointer to the option information with the given name, NULL if either the interface ID is not valid, or the name does not match any options
Definition at line 405 of file bgpstream.c.
References bgpstream_get_data_interface_options().
int bgpstream_get_data_interface_options (bgpstream_t * bs, bgpstream_data_interface_id_t if_id, bgpstream_data_interface_option_t ** opts)
Get a list of valid option types for the given data interface.
Parameters
bs pointer to a BGP Stream instance
if_id ID of the interface to get option names for in the returned array
[out] opts set to a borrowed pointer to an array of options
Returns
the number of elements in the opts array
Note
the returned array belongs to BGP Stream. It must not be freed by the user.
Definition at line 353 of file bgpstream.c.
References ARR_CNT, BGPSTREAM_DATA_INTERFACE_BROKER, BGPSTREAM_DATA_INTERFACE_CSVFILE, BGPSTREAM_DATA_INTERFACE_MYSQL, BGPSTREAM_DATA_INTERFACE_SINGLEFILE, and BGPSTREAM_DATA_INTERFACE_SQLITE.
Referenced by bgpstream_get_data_interface_option_by_name().
int bgpstream_get_data_interfaces (bgpstream_t * bs, bgpstream_data_interface_id_t ** if_ids)
Get a list of data interfaces that are currently supported.
Parameters
bs pointer to the BGP Stream instance in the returned array
[out] if_ids set to a borrowed pointer to an array of bgpstream_datasource_type_t values
Returns
the number of elements the the if_ids array
Note
the returned array belongs to BGP Stream. It must not be freed by the user.
Definition at line 321 of file bgpstream.c.
References ARR_CNT.
int bgpstream_get_next_record (bgpstream_t * bs, bgpstream_record_t * record)
Retrieve from the stream, the next record that matches configured filters.
Parameters
bs pointer to a BGP Stream instance to get record from
record pointer to a bgpstream record instance created using bgpstream_record_create
Returns
>0 if a record was read successfully, 0 if end-of-stream has been reached, <0 if an error occurred.
The record passed to this function may be reused for subsequent calls if state for previous records is not needed (i.e. the records are processed independently of each other). If records are not processed independently, then a new record must be created for each call to this function.
Definition at line 519 of file bgpstream.c.
References bgpstream_record_clear().
void bgpstream_set_blocking (bgpstream_t * bs)
Configure the interface to blocks waiting for new data instead of returning end-of-stream if no more data is available.
Parameters
bs pointer to a BGP Stream instance to put into blocking mode
Definition at line 470 of file bgpstream.c.
void bgpstream_set_data_interface (bgpstream_t * bs, bgpstream_data_interface_id_t if_id)
Set the data interface that BGP Stream uses to find BGP data.
Parameters
bs pointer to a BGP Stream instance to configure
if_id ID of the data interface to use
Definition at line 451 of file bgpstream.c.
void bgpstream_set_data_interface_option (bgpstream_t * bs, bgpstream_data_interface_option_t * option_type, const char * option_value)
Set a data interface option.
Parameters
bs pointer to a BGP Stream instance to configure
option_type pointer to the option to set
option_value value to set the option to
Use the bgpstream_get_data_interface_options function to discover the set of options for an interface.
Definition at line 433 of file bgpstream.c.
int bgpstream_start (bgpstream_t * bs)
Start the given BGP Stream instance.
Parameters
bs pointer to a BGP Stream instance to start
Returns
0 if the stream was started successfully, -1 otherwise
This function must be called after all configuration functions, and before the first call to bgpstream_get_next_record.
Definition at line 484 of file bgpstream.c.
void bgpstream_stop (bgpstream_t * bs)
Stop the given BGP Stream instance.
Parameters
bs pointer to a BGP Stream instance to stop
Definition at line 566 of file bgpstream.c.