bgpstream_utils_as_path_store.h File Reference
Header file that exposes the public interface of the BGPStream AS Path Store.
Data Structures
struct bgpstream_as_path_store_path_id
Represents a single path in the store.
struct bgpstream_as_path_store_path_iter
Store path iterator structure.
Typedefs
Public Opaque Data Structures
typedef struct
bgpstream_as_path_store bgpstream_as_path_store_t
Opaque pointer to an AS Path Store object.
typedef struct
bgpstream_as_path_store_path bgpstream_as_path_store_path_t
Opaque pointer to an AS Path Store Path object.
Functions
Public API Functions
bgpstream_as_path_store_t * bgpstream_as_path_store_create ()
Create a new AS Path Store.
void bgpstream_as_path_store_destroy (bgpstream_as_path_store_t *store)
Destroy the given AS Path Store.
uint32_t bgpstream_as_path_store_get_size (bgpstream_as_path_store_t *store)
Get the number of paths in the store.
int bgpstream_as_path_store_insert_path (bgpstream_as_path_store_t *store, uint8_t *path_data, uint16_t path_len, int is_core, bgpstream_as_path_store_path_id_t *id)
Directly add the given path to the store and return the path ID.
int bgpstream_as_path_store_get_path_id (bgpstream_as_path_store_t *store, bgpstream_as_path_t *path, uint32_t peer_asn, bgpstream_as_path_store_path_id_t *id)
Get the ID of the given path from the store.
bgpstream_as_path_store_path_t * bgpstream_as_path_store_get_store_path (bgpstream_as_path_store_t *store, bgpstream_as_path_store_path_id_t id)
Get a (borrowed) pointer to the Store Path for the given Path ID.
void bgpstream_as_path_store_iter_first_path (bgpstream_as_path_store_t *store)
Reset the internal iterator to the first Path in the store.
void bgpstream_as_path_store_iter_next_path (bgpstream_as_path_store_t *store)
Advance the internal iterator to the next Path in the store.
int bgpstream_as_path_store_iter_has_more_path (bgpstream_as_path_store_t *store)
Check if the internal iterator is pointing to a valid path.
bgpstream_as_path_store_path_t * bgpstream_as_path_store_iter_get_path (bgpstream_as_path_store_t *store)
Get the current path from the iterator.
bgpstream_as_path_store_path_id_t bgpstream_as_path_store_iter_get_path_id (bgpstream_as_path_store_t *store)
Get the path ID of the current path from the iterator.
bgpstream_as_path_t * bgpstream_as_path_store_path_get_path (bgpstream_as_path_store_path_t *store_path, uint32_t peer_asn)
Convert the given store path to a native BGPStream AS Path.
void bgpstream_as_path_store_path_iter_reset (bgpstream_as_path_store_path_t *store_path, bgpstream_as_path_store_path_iter_t *iter, uint32_t peer_asn)
Reset the given store path iterator.
bgpstream_as_path_seg_t * bgpstream_as_path_store_path_get_next_seg (bgpstream_as_path_store_path_iter_t *iter)
Get the next segment from the given store path.
uint32_t bgpstream_as_path_store_path_get_idx (bgpstream_as_path_store_path_t *store_path)
Get the internal index of the given store path.
int bgpstream_as_path_store_path_is_core (bgpstream_as_path_store_path_t *store_path)
Check if the given store path is a core path (i.e.
bgpstream_as_path_t * bgpstream_as_path_store_path_get_int_path (bgpstream_as_path_store_path_t *store_path)
Get a pointer to the internal path structure from the store path.
Variables
uint32_t path_hash
An internal hash of the origin ASN segment of the path.
uint16_t path_id
ID of the path within the origin pathset.
Public Data Structures
typedef struct
bgpstream_as_path_store_path_iter bgpstream_as_path_store_path_iter_t
Store path iterator structure.
struct
bgpstream_as_path_store_path_id __attribute__ ((packed)) bgpstream_as_path_store_path_id_t
Represents a single path in the store.
Detailed Description
Header file that exposes the public interface of the BGPStream AS Path Store.
Author
Chiara Orsini, Alistair King
Definition in file bgpstream_utils_as_path_store.h.
Typedef Documentation
typedef struct bgpstream_as_path_store_path_iter bgpstream_as_path_store_path_iter_t
Store path iterator structure.
typedef struct bgpstream_as_path_store_path bgpstream_as_path_store_path_t
Opaque pointer to an AS Path Store Path object.
Definition at line 63 of file bgpstream_utils_as_path_store.h.
typedef struct bgpstream_as_path_store bgpstream_as_path_store_t
Opaque pointer to an AS Path Store object.
Definition at line 60 of file bgpstream_utils_as_path_store.h.
Function Documentation
struct bgpstream_as_path_store_path_id __attribute__ ((packed))
Represents a single path in the store.
A path ID should be treated as an opaque identifier.
Represents a single path in the store.
Simple ASN AS Path Segment.
The total number of paths in the store
The currently iterated pathset
The current path within the current pathset
Definition at line 59 of file bgpstream_utils_as_path_store.c.
bgpstream_as_path_store_t* bgpstream_as_path_store_create ()
Create a new AS Path Store.
Returns
pointer to the created store if successful, NULL otherwise
Definition at line 181 of file bgpstream_utils_as_path_store.c.
References bgpstream_as_path_store_destroy(), and malloc_zero().
void bgpstream_as_path_store_destroy (bgpstream_as_path_store_t * store)
Destroy the given AS Path Store.
Parameters
store pointer to the store to destroy
Definition at line 204 of file bgpstream_utils_as_path_store.c.
Referenced by bgpstream_as_path_store_create().
int bgpstream_as_path_store_get_path_id (bgpstream_as_path_store_t * store, bgpstream_as_path_t * path, uint32_t peer_asn, bgpstream_as_path_store_path_id_t * id)
Get the ID of the given path from the store.
Parameters
store pointer to the store
path pointer to the path to get the ID for
peer_asn ASN of the peer that observed this path
[out] path_id pointer to a path ID structure to store the ID into
Returns
0 if the ID was populated correctly, -1 otherwise
If the path is not already in the store, it will be added
Definition at line 266 of file bgpstream_utils_as_path_store.c.
References BGPSTREAM_AS_PATH_SEG_ASN, bgpstream_as_path::seg_cnt, and bgpstream_as_path_seg::type.
uint32_t bgpstream_as_path_store_get_size (bgpstream_as_path_store_t * store)
Get the number of paths in the store.
Parameters
store pointer to the store
Returns
the number of paths in the store
Definition at line 221 of file bgpstream_utils_as_path_store.c.
bgpstream_as_path_store_path_t* bgpstream_as_path_store_get_store_path (bgpstream_as_path_store_t * store, bgpstream_as_path_store_path_id_t id)
Get a (borrowed) pointer to the Store Path for the given Path ID.
Parameters
store pointer to the store
id ID of the path to retrieve
Returns
borrowed pointer to the Store Path, NULL if no path exists
If a native BGPStream path is required, use the bgpstream_as_path_store_path_get_path function.
Definition at line 377 of file bgpstream_utils_as_path_store.c.
int bgpstream_as_path_store_insert_path (bgpstream_as_path_store_t * store, uint8_t * path_data, uint16_t path_len, int is_core, bgpstream_as_path_store_path_id_t * id)
Directly add the given path to the store and return the path ID.
Parameters
store pointer to the store
path_data pointer to the (core) path data byte array
path_len the number of bytes in the path_data array
is_core indicates whether the path is a core path [out] path_id pointer to a path ID structure to store the ID into
Returns
0 if the ID was populated correctly, -1 otherwise
Note
this function is designed to be used when deserializing a path store. The bgpstream_as_path_store_get_path_id function should be preferred over this function wherever possible.
unlike the bgpstream_as_path_store_get_path_id function, the path passed to this function will not be altered in any when on insertion. That is, if the is_core flag is set, the path is assumed to already have had the peer segment removed.
Definition at line 302 of file bgpstream_utils_as_path_store.c.
References bgpstream_as_path_populate_from_data_zc().
void bgpstream_as_path_store_iter_first_path (bgpstream_as_path_store_t * store)
Reset the internal iterator to the first Path in the store.
Parameters
store pointer to the store
Definition at line 317 of file bgpstream_utils_as_path_store.c.
bgpstream_as_path_store_path_t* bgpstream_as_path_store_iter_get_path (bgpstream_as_path_store_t * store)
Get the current path from the iterator.
Parameters
store pointer to the store to get the current path from
Returns
pointer to the path
Definition at line 360 of file bgpstream_utils_as_path_store.c.
bgpstream_as_path_store_path_id_t bgpstream_as_path_store_iter_get_path_id (bgpstream_as_path_store_t * store)
Get the path ID of the current path from the iterator.
Parameters
store pointer to the store to get the current path ID from
Returns
path ID structure for the current path
Definition at line 366 of file bgpstream_utils_as_path_store.c.
int bgpstream_as_path_store_iter_has_more_path (bgpstream_as_path_store_t * store)
Check if the internal iterator is pointing to a valid path.
Parameters
store pointer to the store
Returns
1 if the iterator is valid, 0 otherwise
Definition at line 353 of file bgpstream_utils_as_path_store.c.
void bgpstream_as_path_store_iter_next_path (bgpstream_as_path_store_t * store)
Advance the internal iterator to the next Path in the store.
Parameters
store pointer to the store
Definition at line 331 of file bgpstream_utils_as_path_store.c.
uint32_t bgpstream_as_path_store_path_get_idx (bgpstream_as_path_store_path_t * store_path)
Get the internal index of the given store path.
Parameters
store_path pointer to the store path to get the index of
Returns
index of the given path within the store
This function is designed to be used when serializing the entire store, and should be considered internal. The returned index is guaranteed to be in the range [0 -> bgpstream_as_path_store_get_size).
Definition at line 475 of file bgpstream_utils_as_path_store.c.
bgpstream_as_path_t* bgpstream_as_path_store_path_get_int_path (bgpstream_as_path_store_path_t * store_path)
Get a pointer to the internal path structure from the store path.
Parameters
store_path pointer to the store path
Returns
a borrowed pointer to the internal AS Path structure
This function is designed to be used when serializing the entire store, and should be considered internal.
Definition at line 487 of file bgpstream_utils_as_path_store.c.
bgpstream_as_path_seg_t* bgpstream_as_path_store_path_get_next_seg (bgpstream_as_path_store_path_iter_t * iter)
Get the next segment from the given store path.
Parameters
iter pointer to a valid store path iterator
Returns
borrowed pointer to the next segment, NULL if the path has no more segments
Note
the returned pointer is owned by the path. It MUST NOT be destroyed using bgpstream_as_path_seg_destroy. Also, it is only valid as long as the store path is valid.
Definition at line 464 of file bgpstream_utils_as_path_store.c.
References bgpstream_as_path_get_next_seg(), bgpstream_as_path_iter_reset(), bgpstream_as_path_store_path_iter::peerseg, bgpstream_as_path_store_path_iter::pi, and bgpstream_as_path_store_path_iter::spath.
bgpstream_as_path_t* bgpstream_as_path_store_path_get_path (bgpstream_as_path_store_path_t * store_path, uint32_t peer_asn)
Convert the given store path to a native BGPStream AS Path.
Parameters
store_path pointer to a store path to convert
peer_asn ASN of the peer that observed the path being retrieved
Returns
a pointer to a new AS Path object
The user must destroy the returned path using bgpstream_as_path_destroy. Because this function creates a new path object every time, it should be used sparingly. Consider using the store path iterator functions wherever possible.
Definition at line 397 of file bgpstream_utils_as_path_store.c.
References bgpstream_as_path_clear(), bgpstream_as_path_copy(), bgpstream_as_path_create(), bgpstream_as_path_destroy(), BGPSTREAM_AS_PATH_SEG_ASN, and bgpstream_as_path_update_fields().
int bgpstream_as_path_store_path_is_core (bgpstream_as_path_store_path_t * store_path)
Check if the given store path is a core path (i.e.
the peer segment has been removed)
Parameters
store_path pointer to the store path to get the index of
Returns
1 if the path is a core path, 0 otherwise
This function is designed to be used when serializing the entire store, and should be considered internal.
Definition at line 481 of file bgpstream_utils_as_path_store.c.
void bgpstream_as_path_store_path_iter_reset (bgpstream_as_path_store_path_t * store_path, bgpstream_as_path_store_path_iter_t * iter, uint32_t peer_asn)
Reset the given store path iterator.
Parameters
store_path pointer to the store path to iterate over
iter pointer to the store path iterator to reset
peer_asn ASN of the peer that this path was observed by
Definition at line 444 of file bgpstream_utils_as_path_store.c.
References bgpstream_as_path_iter_reset(), BGPSTREAM_AS_PATH_SEG_ASN, bgpstream_as_path_store_path_iter::peerseg, bgpstream_as_path_store_path_iter::pi, and bgpstream_as_path_store_path_iter::spath.
Variable Documentation
uint32_t path_hash
An internal hash of the origin ASN segment of the path.
Definition at line 92 of file bgpstream_utils_as_path_store.h.
uint16_t path_id
ID of the path within the origin pathset.
Definition at line 95 of file bgpstream_utils_as_path_store.h.