bgpstream_utils_id_set.h File Reference
Header file that exposes the public interface of the BGP Stream ID Set.
Typedefs
Opaque Data Structures
typedef struct bgpstream_id_set bgpstream_id_set_t
Opaque structure containing a ID set instance.
Functions
Public API Functions
bgpstream_id_set_t * bgpstream_id_set_create ()
Create a new ID set instance.
int bgpstream_id_set_insert (bgpstream_id_set_t *set, uint32_t id)
Insert a new ID into the given set.
int bgpstream_id_set_exists (bgpstream_id_set_t *set, uint32_t id)
Check whether an ID exists in the set.
int bgpstream_id_set_size (bgpstream_id_set_t *set)
Get the number of IDs in the given set.
int bgpstream_id_set_merge (bgpstream_id_set_t *dst_set, bgpstream_id_set_t *src_set)
Merge two ID sets.
void bgpstream_id_set_destroy (bgpstream_id_set_t *set)
Destroy the given ID set.
void bgpstream_id_set_clear (bgpstream_id_set_t *set)
Empty the id set.
Detailed Description
Header file that exposes the public interface of the BGP Stream ID Set.
Author
Chiara Orsini
Definition in file bgpstream_utils_id_set.h.
Typedef Documentation
typedef struct bgpstream_id_set bgpstream_id_set_t
Opaque structure containing a ID set instance.
Definition at line 43 of file bgpstream_utils_id_set.h.
Function Documentation
void bgpstream_id_set_clear (bgpstream_id_set_t * set)
Empty the id set.
Parameters
set a pointer to the id set to clear
Definition at line 122 of file bgpstream_utils_id_set.c.
bgpstream_id_set_t* bgpstream_id_set_create ()
Create a new ID set instance.
Returns
a pointer to the structure, or NULL if an error occurred
Definition at line 53 of file bgpstream_utils_id_set.c.
References bgpstream_id_set_destroy().
void bgpstream_id_set_destroy (bgpstream_id_set_t * set)
Destroy the given ID set.
Parameters
set pointer to the ID set to destroy
Definition at line 116 of file bgpstream_utils_id_set.c.
Referenced by bgpstream_id_set_create().
int bgpstream_id_set_exists (bgpstream_id_set_t * set, uint32_t id)
Check whether an ID exists in the set.
Parameters
set pointer to the ID set
id the ID to check
Returns
0 if the ID is not in the set, 1 if it is in the set
Definition at line 84 of file bgpstream_utils_id_set.c.
int bgpstream_id_set_insert (bgpstream_id_set_t * set, uint32_t id)
Insert a new ID into the given set.
Parameters
set pointer to the id set
id id to insert in the set
Returns
1 if the id was inserted, 0 if it already existed, -1 if an error occurred
Todo:
we should always check the return value from khash funcs
Definition at line 71 of file bgpstream_utils_id_set.c.
Referenced by bgpstream_id_set_merge().
int bgpstream_id_set_merge (bgpstream_id_set_t * dst_set, bgpstream_id_set_t * src_set)
Merge two ID sets.
Parameters
dst_set pointer to the set to merge src into
src_set pointer to the set to merge into dst
Returns
0 if the sets were merged succsessfully, -1 otherwise
Definition at line 94 of file bgpstream_utils_id_set.c.
References bgpstream_id_set_insert().
int bgpstream_id_set_size (bgpstream_id_set_t * set)
Get the number of IDs in the given set.
Parameters
set pointer to the id set
Returns
the size of the id set
Definition at line 111 of file bgpstream_utils_id_set.c.