bgpstream_elem_generator.h File Reference
Header file that exposes the protected interface of the bgpstream elem generator.
Typedefs
Public Opaque Data Structures
typedef struct
bgpstream_elem_generator bgpstream_elem_generator_t
Functions
Protected API Functions
bgpstream_elem_generator_t * bgpstream_elem_generator_create ()
Create a new Elem generator.
void bgpstream_elem_generator_destroy (bgpstream_elem_generator_t *generator)
Destroy the given generator.
void bgpstream_elem_generator_clear (bgpstream_elem_generator_t *generator)
Clear the generator ready for re-use.
int bgpstream_elem_generator_is_populated (bgpstream_elem_generator_t *generator)
Check if the generator has been populated.
int bgpstream_elem_generator_populate (bgpstream_elem_generator_t *generator, struct struct_bgpstream_record_t *record)
Populate a generator with elems from the given record.
bgpstream_elem_t * bgpstream_elem_generator_get_next_elem (bgpstream_elem_generator_t *generator)
Get the next elem from the generator.
Detailed Description
Header file that exposes the protected interface of the bgpstream elem generator.
Author
Alistair King
Definition in file bgpstream_elem_generator.h.
Function Documentation
void bgpstream_elem_generator_clear (bgpstream_elem_generator_t * generator)
Clear the generator ready for re-use.
Parameters
generator pointer to the generator to clear
Definition at line 709 of file bgpstream_elem_generator.c.
Referenced by bgpstream_record_clear().
bgpstream_elem_generator_t* bgpstream_elem_generator_create ()
Create a new Elem generator.
Returns
pointer to a new Elem generator instance
Currently the elem generator is simply a reusable container for elem records (populated by a call to bgpstream_elem_populate_generator), but it is possible that at some point in the future it may actually generate elem records on the fly.
Definition at line 672 of file bgpstream_elem_generator.c.
References malloc_zero().
Referenced by bgpstream_record_create().
void bgpstream_elem_generator_destroy (bgpstream_elem_generator_t * generator)
Destroy the given generator.
Parameters
generator pointer to the generator to destroy
Definition at line 687 of file bgpstream_elem_generator.c.
References bgpstream_elem_destroy().
Referenced by bgpstream_record_destroy().
bgpstream_elem_t* bgpstream_elem_generator_get_next_elem (bgpstream_elem_generator_t * generator)
Get the next elem from the generator.
Parameters
generator pointer to the generator to retrieve an elem from
Returns
borrowed pointer to the next elem
Note
the memory for the returned elem belongs to the generator.
Definition at line 772 of file bgpstream_elem_generator.c.
Referenced by bgpstream_record_get_next_elem().
int bgpstream_elem_generator_is_populated (bgpstream_elem_generator_t * generator)
Check if the generator has been populated.
Parameters
generator pointer to the generator
Returns
1 if the generator is ready for use, 0 otherwise
Definition at line 717 of file bgpstream_elem_generator.c.
Referenced by bgpstream_record_get_next_elem().
int bgpstream_elem_generator_populate (bgpstream_elem_generator_t * generator, struct struct_bgpstream_record_t * record)
Populate a generator with elems from the given record.
Parameters
generator pointer to the generator to populate
record pointer to a BGP Stream Record instance
Returns
0 if the generator was populated successfully, -1 otherwise
Note
This function may defer processing of the record until each call to bgpstream_elem_generator_next_elem
Definition at line 722 of file bgpstream_elem_generator.c.
References struct_bgpstream_record_t::bd_entry, BGPSTREAM_RECORD_STATUS_VALID_RECORD, and struct_bgpstream_record_t::status.
Referenced by bgpstream_record_get_next_elem().