CAIDA\BGPStreamWeb\DataBrokerBundle\Entity\BgpData:
    type: entity
    table: bgp_data
    readOnly: true
    repositoryClass: CAIDA\BGPStreamWeb\DataBrokerBundle\Repository\BgpDataRepository
    indexes:
        file_time_idx:
            columns:
                - file_time
        collector_type_filetime_idx:
            columns:
                - collector_type_id
                - file_time
        collector_type_id_idx:
            columns:
                - collector_type_id
    id:
        collectorType:
            associationKey: true
        fileTime:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: file_time
    fields:
        webSize:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: web_size
        ts:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
    manyToOne:
        collectorType:
            targetEntity: CollectorType
            inversedBy: null
        dumpInfo:
            targetEntity: DumpInfo
            inversedBy: data
            joinColumns:
                collector_type_id:
                    referencedColumnName: collector_type_id
    lifecycleCallbacks: {  }
