CAIDA\BGPStreamWeb\DataBrokerBundle\Entity\BgpData:
    type: entity
    table: bgp_data
    indexes:
        bgp_data_ibfk_2:
            columns:
                - bgp_type_id
        file_time_idx:
            columns:
                - file_time
        ts_collector_type_filetime_idx:
            columns:
                - ts
                - file_time
                - bgp_type_id
                - collector_id
        type_filetime_idx:
            columns:
                - file_time
                - bgp_type_id
        IDX_842B7360670BAFFE:
            columns:
                - collector_id
    id:
        fileTime:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: file_time
    fields:
        webSize:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: web_size
        ts:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
    oneToOne:
        collector:
            targetEntity: Collector
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                collector_id:
                    referencedColumnName: id
            orphanRemoval: false
        bgpType:
            targetEntity: BgpType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                bgp_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
