CAIDA\BGPStreamWeb\DataBrokerBundle\Entity\BgpType:
    type: entity
    table: bgp_types
    readOnly: true
    uniqueConstraints:
        name:
            columns:
                - name
        path:
            columns:
                - path
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        path:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    manyToMany:
        collectors:
            targetEntity: Collector
            cascade: {  }
            mappedBy: bgpTypes
    oneToMany:
        data:
            targetEntity: BgpData
            cascade: {  }
            mappedBy: bgpType
    lifecycleCallbacks: {  }
