CAIDA\BGPStreamWeb\DataBrokerBundle\Entity\Collector:
    type: entity
    table: collectors
    readOnly: true
    indexes:
        project_id:
            columns:
                - project_id
    uniqueConstraints:
        name:
            columns:
                - name
        path:
            columns:
                - path
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        path:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    manyToOne:
        project:
            targetEntity: Project
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        data:
            targetEntity: BgpData
            cascade: {  }
            mappedBy: collector
    lifecycleCallbacks: {  }
