CAIDA\BGPStreamWeb\DataBrokerBundle\Entity\Project:
    type: entity
    table: projects
    readOnly: true
    repositoryClass: CAIDA\BGPStreamWeb\DataBrokerBundle\Repository\ProjectRepository
    uniqueConstraints:
        name:
            columns:
                - name
        path:
            columns:
                - path
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        path:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        fileExt:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: file_ext
    oneToMany:
        collectors:
            targetEntity: Collector
            cascade: {  }
            mappedBy: project
    lifecycleCallbacks: {  }
